### ISSUE TITLE
Adding new files defaults to them having a build action of "Does not participate in the build"

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#100]
When I add new files to my CPS based project, or if I install a NuGet package that delivers content files, the files get added with a build action:

![image](https://cloud.githubusercontent.com/assets/3176632/12028249/31b6ea58-adcc-11e5-8b81-6024081d39e9.png)

If anyone can give me a nudge in the right direction regarding how I can go about ensuring that when files are added they are set as "Content" - it would be greatly appreciated ;)

**Comment by aienabled** [comment]
My answer here is relevant to this issue https://github.com/Microsoft/VSProjectSystem/issues/99

**Comment by dazinator** [comment]
@aienabled - brilliant stuff! Thanks once again.

**Comment by dazinator** [comment]
Closign this because I now know why this happens thanks to aienabled.
