### ISSUE TITLE
[Question] Has anyone got ASCX (or ASPX) files working with their project system?

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#105]
I am really struggling trying to get ASCX files working with my project system.

I created an item template that brings in the ascx, code behind, and designer files, by creating a vstemplate like this:

``` xml

 <TemplateContent>
    <References>
      <Reference>
        <Assembly>System</Assembly>
        <Assembly>System.Web</Assembly>
      </Reference>
    </References>

    <ProjectItem SubType="" TargetFileName="$fileinputname$.ascx" ReplaceParameters="true">View.ascx</ProjectItem>
    <ProjectItem SubType="ASPXCodeBehind" TargetFileName="$fileinputname$.ascx.cs" ReplaceParameters="true">View.ascx.cs</ProjectItem>
    <ProjectItem SubType="" TargetFileName="$fileinputname$.ascx.designer.cs" ReplaceParameters="true">View.ascx.designer.cs</ProjectItem>   
  
  </TemplateContent>  

```

This works in that I can add these files to my project system.

I then have defined the "rules" for my project system, such that these files are recognised as content types, and are nested appropriately - even though that has lead to the issue #102 which occurs when I unload and reload the project - will ignore that issue for now.

However even after the project items are all in place and displaying in solution explorer like I want them.. they aren't "behaving" like they do in a web project in that, changing the ascx markup and then saving, doesn't appear to re-generate the designer file.

How can I get the asp.net tooling to run to generate the designer.cs file when changes to the markup are made? 

For example, if you modify the markup by adding a button:

```xml

<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="View1.ascx.cs" Inherits="DnnExtension87.View1" %>
<div>
    <asp:Button runat="server" ID="button1"/>
</div>
```

Then when you save the file, the designer.cs file is still empty:

```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnnExtension87
{
    public partial class View1
    {
    }
}
```
Any tips from you guru's out there are much welcomed!

**Comment by dazinator** [comment]
One option I am looking at right now is the possibility of using an open source, third party command line to generate the designer files from the ascx file: http://sourceforge.net/projects/redesigner/

This approach would mean I would have to be able to detect when the ascx file was edited so that I could call this command line to generate the ascx. Not currently sure how best to do that.

**Comment by adrianvmsft** [comment]
There is already a mechanism that pretty much does that: single file generators. It already works in CPS for .resx and .tt files [T4 text templates files](https://msdn.microsoft.com/en-us/library/bb126445.aspx)

This page describes how to create and register a single file generator:
https://msdn.microsoft.com/en-us/library/bb166817.aspx

Unfortunately, I don't know how the default ascx file generation works in VS - I couldn't find it in the single file generator registry on my box.

One note: the single file generator feature is activated in CPS if a capability named "SingleFileGenerators" is defined in your project. By default that is already included in the project type via the default targets (Microsoft.Common.CurrentVersion.targets), but if you completely changed the targets you may need to make sure it is defined.

**Comment by dazinator** [comment]
@adrianvmsft - ok thanks - l'll take a look at the single file generator approach.. I have allready got code in place to detect modifications to ascx files and invoke a custom action without using the single file generator approach, but it sounds like i should probably switch mechanisms to this new approach to fit in better with the cps ecosystem.
Unfortunately most of the hard stuff is in the code that needs to interpret the ascx file and code gen the designer file - and it sounds like there is nothing in built that i can leverage in this regard :(

**Comment by dazinator** [comment]
I have gone down the single file generator route, my generator is fired from a normal c# library project if I set the "custom tool" in the properties window to be the name of my generator.

I am now struggling over how to give an `ascx` file, within my own project system, the ability to have a custom tool. I'll raise a seperate issue for that though.
