### ISSUE TITLE
Item templates --> subtype of file in vstemplate not set when added to project

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#106]
If you create an item template:
```xml
<TemplateContent>
    <References>
      <Reference>
        <Assembly>System</Assembly>
        <Assembly>System.Web</Assembly>
      </Reference>
    </References>

    <ProjectItem SubType="" TargetFileName="$fileinputname$.ascx" ReplaceParameters="true">View.ascx</ProjectItem>
    <ProjectItem SubType="ASPXCodeBehind" TargetFileName="$fileinputname$.ascx.cs" ReplaceParameters="true">View.ascx.cs</ProjectItem>
    <ProjectItem SubType="" TargetFileName="$fileinputname$.ascx.designer.cs" ReplaceParameters="true">View.ascx.designer.cs</ProjectItem>   
  
  </TemplateContent>  
```

Note: the second item `<ProjectItem SubType="ASPXCodeBehind" `

When you then `Add New Item` to your CPS project and pick this item template, it adds the 3 files but the SubType it never set:

```
 <Compile Include="View1.ascx.cs">
      <DependentUpon>View1.ascx</DependentUpon>
    </Compile>
    <Compile Include="View1.ascx.designer.cs">
      <DependentUpon>View1.ascx</DependentUpon>
    </Compile>
<ItemGroup>  
    <Content Include="View1.ascx" />
  </ItemGroup>
``` 

Would you not expect for the SubType to also be added, like so - as per the vstemplate?

```
 <Compile Include="View1.ascx.cs">
      <DependentUpon>View1.ascx</DependentUpon>
      <SubType>ASPXCodeBehind</SubType>
    </Compile>

```

**Comment by adrianvmsft** [comment]
Does it work properly (e.g. you get the right editor and editing experience) if you manually edit the project and set the property? The reason I am asking is that it is very possible that the editor won't work with CPS projects at this point. If that is the case, it may not be worth digging further on how to set the property in the first place:(.

If it works properly when manually set, than I would suggest trying to see if you can get it working in an item template that you use with a standard C# project (it didn't work for me in my attempts, it is possible that the template engine may try additional checks on what editors are supported).

If that still doesn't work, there is another possibility to set the property - writing a custom wizard extension and setting it from the IWizard ProjectItemFinishedGenerating method via DTE. My concern though is that CPS has some limited support for DTE, so I am not sure if that would work. Again, I would suggest getting it working for the standard C# project first.

You can find more details here:
https://msdn.microsoft.com/en-us/library/ms171411.aspx
https://msdn.microsoft.com/en-us/library/Microsoft.VisualStudio.TemplateWizard.IWizard.aspx

Here is a snippet that sets the IncludeInVSIX property for .foo files

```csharp
    public class MyWizardImpl : IWizard
    {
        // ...
        public void ProjectItemFinishedGenerating(EnvDTE.ProjectItem projectItem)
        {
            var fileCount = projectItem.FileCount;
            for (short i = 0 ; i < fileCount; i++)
            {
                if (fileName.EndsWith(".foo", StringComparison.OrdinalIgnoreCase))
                {
                    projectItem.Properties.Item("VsixContentItemObjectExtender.IncludeInVSIX").Value = true;
                }
            }
        }

    }
```

Hope this helps.

**Comment by dazinator** [comment]
Thanks @adrianvmsft much appreciated. I will give those suggestions a try and get back to you. Custom wizard may be a bit tricky as I am already using the NuGet wizard and you can only have one wizard.. but I saw an article about wrapping the nuget wizard within your own wizard so I'd have to give that a go. Cheers.

**Comment by adrianvmsft** [comment]
You should be able to have multiple wizards. Templates that come with the project system extensibility use 2 wizards (nuget + custom) - see snippet below.

One note about it - from my experience it looked like the order wizards specified seemed to matter.

```xml
  <WizardExtension>
    <Assembly>Microsoft.VisualStudio.ProjectSystem.SDK.Wizard, Version=14.1.0.0, Culture=Neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName>Wizard.ChildWizardImpl</FullClassName>
  </WizardExtension>
  <WizardExtension>
    <Assembly>NuGet.VisualStudio.Interop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName>NuGet.VisualStudio.TemplateWizard</FullClassName>
  </WizardExtension>
```

**Comment by dazinator** [comment]
@adrianvmsft  - I have looked at having multiple wizards before, and came accross answers like this: https://social.msdn.microsoft.com/Forums/vstudio/en-US/87498bf1-9ee3-4e85-a5b7-e30401aaa265/problem-vstemplate-only-uses-first-wizard-extension?forum=vsx which suggested it wasn't possible! Happy to give it a go though.

**Comment by adrianvmsft** [comment]
I haven't heard back, so I hope this worked fine... I am closing this issue, please reactivate or file a new issue if you still run into issues.

**Comment by dazinator** [comment]
Yep soz for the lack of a reply, havent been able to test this quite yet
but i'll update once I have :)
