### ISSUE TITLE
Cannot get properties window for my file type working.. [Help]

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#107]
I would like for `ascx` files within my project system, to have a properties window, and one property in particular that is important is the ability to set the "custom tool" - as I have created a `single file generator` for ascx files. 

I followed the docs, and have included a rule for `ascx` files:

```xml
 <PropertyPageSchema Include="
                        $(MSBuildThisFileDirectory)Rules\AscxFile.xaml;                        
                        ">     
      <Context>File;</Context>
    </PropertyPageSchema>
```

In my `AscxFile.xaml` rule,  I am specifying the properties that I want for ascx files:

```xml

<Rule
	Name="AscxFile"
	DisplayName="General"
	PageTemplate="generic"
	Description="File Properties"
	xmlns="http://schemas.microsoft.com/build/2009/properties">
    <Rule.DataSource>
        <DataSource Persistence="ProjectFile" HasConfigurationCondition="false" ItemType="Content"/>
    </Rule.DataSource>

    <Rule.Categories>
        <Category Name="Advanced" DisplayName="Advanced" />
        <Category Name="Misc" DisplayName="Misc" />
    </Rule.Categories>   
   
    <DynamicEnumProperty
      Name="{}{ItemType}"
      DisplayName="Build Action"
      Category="Advanced"
      Description="How the file relates to the build and deployment processes."
      EnumProvider="ItemTypes" />

    <EnumProperty
      Name="CopyToOutputDirectory"
      DisplayName="Copy to Output Directory"
      Category="Advanced"
      Description="Specifies the source file will be copied to the output directory.">
        <EnumValue Name="Never" DisplayName="Do not copy" />
        <EnumValue Name="Always" DisplayName="Copy always" />
        <EnumValue Name="PreserveNewest" DisplayName="Copy if newer" />
    </EnumProperty>

    <StringProperty
      Name="Generator"
      Category="Advanced"
      DisplayName="Custom Tool"
      Description="Specifies the tool that transforms a file at design time and places the output of that transformation into another file. For example, a dataset (.xsd) file comes with a default custom tool." />

    <StringProperty
    Name="Identity"
    Visible="false"
    ReadOnly="true"
    Category="Misc"
    Description="The item specified in the Include attribute.">
        <StringProperty.DataSource>
            <DataSource Persistence="Intrinsic" ItemType="Content" PersistedName="Identity" />
        </StringProperty.DataSource>
    </StringProperty>



    <StringProperty Name="FullPath" DisplayName="Full Path" ReadOnly="true" Category="Misc" Description="Location of the file.">
        <StringProperty.DataSource>
            <DataSource Persistence="Intrinsic" ItemType="Content" PersistedName="FullPath" />
        </StringProperty.DataSource>
    </StringProperty>

    <StringProperty
    Name="FileNameAndExtension"
    DisplayName="File Name"
    ReadOnly="true"
    Category="Misc"
    Description="Name of the file or folder.">
        <StringProperty.DataSource>
            <DataSource Persistence="Intrinsic" ItemType="Content" PersistedName="FileNameAndExtension" />
        </StringProperty.DataSource>
    </StringProperty>


    <BoolProperty Name="Visible" Visible="False" />

    <StringProperty Name="Link" Visible="false">
        <StringProperty.Metadata>
            <NameValuePair Name="DoNotCopyAcrossProjects" Value="true" />
        </StringProperty.Metadata>
    </StringProperty>

    <StringProperty Name="SubType" Visible="false" />   

</Rule>

```

However when I select the ascx file in solution explorer - its properties window is empty:

![image](https://cloud.githubusercontent.com/assets/3176632/12278954/0e3aa248-b97c-11e5-8188-a7e35a9dc425.png)

If I right click on the file, and click properties to bring up the properties pages - I can see its added an additional "general" menu item, and then I can see the properties:

![image](https://cloud.githubusercontent.com/assets/3176632/12279420/e8b2a266-b97e-11e5-9c80-55cb09fa2f01.png)

I am failing to understand how I can add a "custom tool" property to the existing "general properties" for my ascx file, and how I can make these display on the property window.. :(

Would appreciate any pointers with this.

Thanks.

**Comment by Tobist** [comment]
Are there any updates about this issue?

**Comment by dazinator** [comment]
@Tobist - nope I;ve not had any response, pretty sure I must be missing something but it's not obvious to me!

**Comment by aienabled** [comment]
The Properties browser works fine for me. I think you need to specify:
```XML
<Context>File;BrowseObject</Context>
```
Not only "File".

**Comment by Tobist** [comment]
Yeah, that works for the standard treeprovider. But with my own tree provider I don't know what input is needed in the browseobject input of the `NewTree`-method. But that has nothing to do with this issue...

**Comment by dazinator** [comment]
@aienabled thanks for that, i'll try those suggestions out!

**Comment by adrianvmsft** [comment]
Hi @dazinator,
I just wanted to check with you to see if you still have this problem.

Thanks,
Adrian

**Comment by dazinator** [comment]
Using my own ItemType instead of "Content" fixed this for me. Not ideal as I now have to change some msbuild tooling that works explicitly with `content` item types, to include my custom item type - but it solves the problem so I am happy! Cheers
