### ISSUE TITLE
Add a Single File Generator Item Template?

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#110]
The item templates that show up under the extensibility category when I add an item to my CPS project are really great for helping me to explore the different extensibility points available. Could you include a template for "Single File Generator" ?

**Comment by adrianvmsft** [comment]
Thank you for the suggestion, hopefully the new documentation added in #118 should clarify the process of adding a new single file generator.
I am going to won't fix this issue for now, as I don't think having an item template for single file generators would add much value comparing to the newly added documentation (plus it would also involve a significant set of manual steps - change targets, add new item type, etc)

We will reconsider it if we get enough requests.

Thanks!
Adrian
