### ISSUE TITLE
Using ProjectType with another VSIX Project

### ISSUE THREAD

**Issue by DominikGrabiec** [Microsoft/VSProjectSystem#114]
Is it possible to use the Project Type generator and have the resulting projects usable in a solution with another project that generates the VSIX? 

What do I need to do and change to make this possible?
Or is it fundamentally not doable and I have to implement the Project Type without CPS?

**Comment by adrianvmsft** [comment]
Just to make sure I understand you question, by "resulting projects", I assume you refer to:
a) the Project Type project itself that was generated by the vsix (sometimes we refer to them as 2nd party)

and not

b) projects of that project type (what your customers would create, which sometimes we refer to them as 3rd party).

It should be possible, the ProjectSystem Extensibility vsix is pretty much a regular vsix project. You will need to merge the content though.

Hope this helps,
Adrian

**Comment by adrianvmsft** [comment]
I am going to close this issue, feel free to reactivate if you still have problems.

Thanks,
Adrian
