### ISSUE TITLE
Make IVsReferenceManagerUserAsync and ExportIVsReferenceManagerUserAsync

### ISSUE THREAD

**Issue by jkoritzinsky** [Microsoft/VSProjectSystem#124]
These interfaces and attributes are referenced in the documentation in the repo as currently not public. They do enable useful features, and they are currently referenced. I suggest either publicizing the APIs (first choice), or remove the references to them in the documentation (2nd choice).

**Comment by lifengl** [comment]
Yes, it appears to be a mistake.  We will fix that.

**Comment by adrianvmsft** [comment]
Good news, this issue was fixed in VS "15" - they are now public.
Please let us know if you still run into issues.
