### ISSUE TITLE
Default value for BoolProperty

### ISSUE THREAD

**Issue by viktoriad** [Microsoft/VSProjectSystem#133]
How to show default value for BoolProperty? E.g. I have
<BoolProperty Name="MyPropety" DisplayName="My property" Category="Advanced" />
When opening property page, the value is set to nothing if I don't have the property in the msbuild project. I tried to use Default="True" but it didn't change anything. How would I show default values for them?

**Comment by adrianvmsft** [comment]
MSBuild needs to know that default value. Which means you will typically specify it in a .props file that gets imported by your project. (You could also use a .targets file or the project itself.)

For example, let's suppose you are adding the following property BoolProperty to the project that you would like to have the default value true (I used a rule created using the XAML Rule template, and changed HasConfigurationCondition to false for simplicity).

```xml
<BoolProperty Category="General" Name="BoolProperty" DisplayName="My Bool Property" Visible="True" Description="Sample bool property" Default="true"/>
```
You can add specify the default value in `CustomProject.Default.props`:
```xml
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
     <!-- ... -->
    <BoolProperty>true</BoolProperty>
  </PropertyGroup>
```
Thanks,
Adrian
