### ISSUE TITLE
Help to explain what can I do using "Project Deploy"? 

### ISSUE THREAD

**Issue by MarioHsiao** [Microsoft/VSProjectSystem#139]
We usually use "Ctrl+Shift+B" to Build Solution, always use "F5" to Start Debugging.
So what can I do for using "Project Deploy"? Use it for something particularly or what as usually ?

**Comment by adrianvmsft** [comment]
Deploy can be used for example for deploying to a device or a web server. For example, you can build and run/debug everything locally, and once you are satisfied with your implementation, you may want to deploy to the live server.

CPS exposes an extensibility point for that via the [IDeployProvider](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/IDeployProvider.md) interface

**Comment by adrianvmsft** [comment]
I am closing this issue, please reactivate if you need additional details.
