### ISSUE TITLE
Provide a reference implementation

### ISSUE THREAD

**Issue by hmemcpy** [Microsoft/VSProjectSystem#14]
First, thank you for making this information  finally public! I've been trying to implement my own project system based on CPS with partial success, and this documentation is extremely helpful! 

It would be awesome if you could make available a complete implementation of a project system to serve as reference. I propose the NuGet project system by @terrajobst, and if at all possible, aspnet vNext!

**Comment by AArnott** [comment]
Hi @hmemcpy! So you found us already (before our blog post).

Yes, we're planning to link to nuproj from our docs as an example.

**Comment by hmemcpy** [comment]
:) Thanks!
