### ISSUE TITLE
"folder.xaml" configurations do not appear on folders durring debugging

### ISSUE THREAD

**Issue by IObsequious** [Microsoft/VSProjectSystem#141]
I would like to thank you in advance for this project. Finally... Finally! we can customize the project experience like a normal human being would...

**Scenario**
•I want to add a simple property to a folder node within a project.

**Problem**
•Configuring the property viz "folder.xaml" does not work. Debugging sessions yield property-naked folders

**Reproduction**
1. Create a new project viz File > New > Project > Templates > Visual C# > Extensibility > Property Type
2. Focus on the *.ProjectType project
3. Find "BuildSystem\Rules". folder
4. Open "folder.xaml"
5. Add a simple property (e.g.  `<StringProperty name="FoonaldTrump" />` )
6. Save. Press F5
7. In Debugger, create a new project from your new Project Type
8. Once project loads, right click project node and choose Add > NewFolder.
9. Right click the folder with your cursor. Look in the properties window. For me, no configurations appear. 

Let me know if this is indeed an issue, or if I need some guidance on how this type of configuration works. FYI: I am able to configure and subsequently see expected results for all of the other files just fine. Keep up the great work!

**Comment by adrianvmsft** [comment]
Unfortunately, CPS doesn't currently support properties on folders. It's on our radar though, hopefully we may be able to get it in for the next version of Visual Studio.

**Comment by adrianvmsft** [comment]
Good news: Folder properties are now supported in the latest versions of Visual Studio 2017! You will need to update the folder.xaml rule to enable this feature (more specifically the datasource persistence):

```xml
<Rule
  Name="Folder"
  DisplayName="General"
  PageTemplate="generic"
  Description="Folder Properties"
  xmlns="http://schemas.microsoft.com/build/2009/properties">
  <Rule.DataSource>
    <DataSource Persistence="ProjectFileFolderItems" HasConfigurationCondition="False" ItemType="Folder" />
  </Rule.DataSource>

  <StringProperty Name="Identity" Visible="false" ReadOnly="true" Category="Misc" />
  <StringProperty Name="FullPath" DisplayName="Full Path" ReadOnly="true" Category="Misc" Description="Location of the folder"/>
  <StringProperty Name="FolderName" DisplayName="Folder Name" ReadOnly="true" Category="Misc" Description="Name of this folder"/>
</Rule>
```
