### ISSUE TITLE
ProjectPropertiesProvider - use?

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#144]
Hello!

I am wondering how to gain access to project properties, as I need to get "output path" property for the project, and I stumbled accross this:

```

  var projectProps = configuredProject.Services.ProjectPropertiesProvider.GetCommonProperties();

```

This returns an `Microsoft.VisualStudio.ProjectSystem.Properties.IProjectProperties` instance, but I can't see any useful methods or properties on this that actual gives property information? Can you give a brief idea of what this is used for?

**Comment by dazinator** [comment]
Worth mentioning, Iam trying to do this within a Single File Generator. I can do this easily from within a VSPackage like so: 

```
               var configManager = project.ConfigurationManager;
               var activeConfig = configManager.ActiveConfiguration;
               var activeConfigPropst = activeConfig.Properties;
               var outputPathProp = activeConfigPropst.Item("OutputPath");
```

However for some reason, when I use this code inside a `Single File Generator` it hangs forever when accessing `configManager.ActiveConfiguration` so I have started to look for another way, and came accross `ProjectPropertiesProvider`

**Comment by adrianvmsft** [comment]
Have you tried this?
https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/property_retrievevalue.md

Thanks,
Adrian

**Comment by dazinator** [comment]
Thanks :-) - I'll close this now!
