### ISSUE TITLE
Is AppDesigner support yet available?  

### ISSUE THREAD

**Issue by kfertitta** [Microsoft/VSProjectSystem#146]
This is a must-have for migrating our custom project systems.

**Comment by adrianvmsft** [comment]
Good news about the app designer, the roslyn team got the App Designer for the .Net Core project system: 

https://github.com/dotnet/roslyn-project-system

Also, as far as I know, it is now open source! I am not familiar with the Roslyn project system repo, but I think the App designer sources are here:
https://github.com/dotnet/roslyn-project-system/tree/master/src/Microsoft.VisualStudio.AppDesigner

Thanks,
Adrian
