### ISSUE TITLE
Project Capability Proposal for Devices

### ISSUE THREAD

**Issue by joj** [Microsoft/VSProjectSystem#149]
I want to add the following capabilities: BuildAndroidTarget, BuildiOSTarget, BuildTvOSTarget, BuildMacOSTarget and BuildWatchOSTarget.

All of these will represent the capability of the project to compile on the specified platform. That, along with the inherited Managed capability will imply that the project is able to compile managed code (in Mono for these platforms) for the specified platform. 

Please advice if these are good enough. I'm basing myself on a Good example (BuildAndroidTarget) and just generalizing. Also, casing is weird because casing is always weird for Apple products... but it is consistent with everything we're doing for those platforms.

Thanks,
joj

**Comment by adrianvmsft** [comment]
I think they look good. The only thing that you may want to consider is using some prefix to avoid potential collisions. Searching through the Visual Studio Sources I didn't find conflicts with these names.

**Comment by joj** [comment]
A prefix like Xamarin? I could do that but that would mean having a brand name, which I rather don't. My intention is to have VC use the same capabilities at some point (not managed, though, but that's implied).

**Comment by adrianvmsft** [comment]
That's a good point. In that case I agree that it is better without a prefix like Xamarin.

**Comment by kallisto** [comment]
What would be the timeline to get this in?

**Comment by joj** [comment]
So, if we have no further comments, can we close this? I'm applying the changes to our targets today unless someone is against it.

**Comment by adrianvmsft** [comment]
Yep, feel free to close it.

**Comment by joj** [comment]
Closing this, then. I will implement in our targets/project system.
