### ISSUE TITLE
CPS fails on property group with only configuration

### ISSUE THREAD

**Issue by carlokok** [Microsoft/VSProjectSystem#151]
(If this is the wrong place for this let me know, I'll move it)
In a project with only a configuration:

```
<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
```

CPS fails inside 

internal static void SplitCanonicalProjectConfigurationName(string projectConfigurationName, out string configurationName, out string platformName)

The projectConfigurationName will have only "Debug" and thus cannot be split.

**Comment by adrianvmsft** [comment]
I took a look at the code, and it indeed, doesn't handle 1 dimension configuration.

**Comment by adrianvmsft** [comment]
Could you provide some details on how you hit this issue?
I am trying to figure out what else may break.

**Comment by carlokok** [comment]
We're trying to port our own project system to this new model (to make sure we're ready for VS15), so far this is the only big issue we've hit, as all our projects currently only have property groups like this.

**Comment by adrianvmsft** [comment]
I tried to repro the issue you are seeing using a new project type, but no luck so far. I am trying to understand what else may fail if we fix this issue.
Could you try to replicate this issue on a clean project type? In which cases do you see this error, when loading the project or perhaps when you try to set some property defined by the property group?

**Comment by carlokok** [comment]
This project shows it with plain vs2017 RC C#'s cps project system (no need for a cps plugin):
[ClassLibrary2.zip](https://github.com/Microsoft/VSProjectSystem/files/608348/ClassLibrary2.zip)

**Comment by adrianvmsft** [comment]
Thanks, I was able to repro the issue with this project!
I have a tentative fix, however I noticed that Visual Studio is very specific about adding the missing "AnyCPU" to the solution file. Every time you open the project (with the fix) it wants to save the .sln.
Did you notice that behavior in your previous implementation?

**Comment by carlokok** [comment]
No I did not. Our previous projects were created in 2015 and were like this. That said, if we can open and "upgrade" to this, I don't mind if it adds the AnyCPU, at least, the first time around.

**Comment by adrianvmsft** [comment]
This should be fixed now in the latest public release of Visual Studio 2017.
