### ISSUE TITLE
Put a space in the category name

### ISSUE THREAD

**Issue by zdimension** [Microsoft/VSProjectSystem#152]
I'm currently using the new Visual Studio Project System Extensibility library to implement a new project type for VS2015. What I would like to do is change the name of the "category" of that type of project. I would like it to be "Visual Basic 6". The problem is that when I create a package using the "Project Type" template, it asks me for a display name (which I set to "Visual Basic 6") and a namespace name (which I set to VB6), buth when I launch the VS experimental hive (with the default template code), the project template name is "Visual Basic 6 Project" but the category at the left is "VB6". I tried changing the line of the .vstemplate file from

``` xml
<ProjectType>VB6</ProjectType>
```

to

``` xml
<ProjectType>Visual Basic 6</ProjectType>
```

but if I do that, then the template simply doesn't appear in the New Project window. I also tried changing the value of the Language and UniqueCapability constants in the MyUnconfiguredProject.cs file, but it doesn't change anything. If I ever change the ProjectType value, the template disappears. I noticed that the category name is in fact the namespace name (and not the "Display name", why?), so it works if I put VisualBasic6, but I can't put spaces. How could I make the category be "Visual Basic 6" ?

**Comment by adrianvmsft** [comment]
I think this is a bug in our SDK template.

For now, I guess best option is to create it without the space and make adjustments to the generated code to insert the space where you need it.

When you say that you would like to change the Category, do you mean the name it gets listed in the New Project Dialog?

**Comment by zdimension** [comment]
Yes, I mean the name in the New Project Dialog, for example in a .vstemplate file, "CSharp" gets changed to "Visual C#" in the dialog, and "VB" gets changed to "Visual Basic". I would like to do a similar thing here.

**Comment by adrianvmsft** [comment]
I was able to get it working by updating these 3 places (in my case I named the category node as Project Type N):

.vstemplate from template project:
```xml
<ProjectType>Project Type N</ProjectType>
```

MyUnfonfiguredProject.cs
```CSharp
internal const string Language = "Project Type N";
```
source.extension.vsixmanifest - I had to update d:TargetPath
```xml
<Asset Type="Microsoft.VisualStudio.ProjectTemplate" d:Source="Project" d:ProjectName="ProjectType1.ProjectTemplate" d:TargetPath="Project Type N" Path="ProjectTemplates" d:VsixSubPath="ProjectTemplates" />
```
It may be possible to further refine this - for example investigating why I had to change d:TargetPath in .vsixmanifest, or if all 3 changes are needed, but hopefully this should get you unblocked.

Thanks,
Adrian

**Comment by zdimension** [comment]
GREAT SCOTT!

Thank you so much, it works now!
zdimension

**Comment by adrianvmsft** [comment]
Good news: we fixed this issue by adding a new language edit box in the wizard, and will be available with the next release of the project system extensibility.
