### ISSUE TITLE
Adding the Store menu to a project subtype

### ISSUE THREAD

**Issue by munyirik** [Microsoft/VSProjectSystem#154]
What's the best way to add a the Store menu (see below) to a project subtype? I used extensibility provided by IVsAppContainer* for deployment but I couldn't find anything for that menu. 

![capture](https://cloud.githubusercontent.com/assets/8389594/19063448/ca599b4e-89b7-11e6-8f78-1e243dc2442b.PNG)

The project I'm working on is https://github.com/ms-iot/ntvsiot

**Comment by adrianvmsft** [comment]
I think your question is related to the more generic VS extensibility, so a better place to ask your question would be:

https://github.com/Microsoft/ExtendVS

Hope this helps,
Adrian

**Comment by munyirik** [comment]
For the benefit of anyone else trying this. The solution is to sent the __VSHPROPID5.VSHPROPID_AppContainer property to true. This will identify your package as an AppContainer project and bring up the menu.
