### ISSUE TITLE
Project capability proposal: DockerCompose

### ISSUE THREAD

**Issue by dazhao-msft** [Microsoft/VSProjectSystem#159]
We're adding a new project system based on CPS in VS 2017 in order to support [Docker Compose](https://docs.docker.com/compose/overview/).

- Project capability to add: **DockerCompose**
- Project extention: **.dcproj**
- Project type GUID: **E53339B2-1760-4266-BCC7-CA923CBCF16C**

**Comment by AArnott** [comment]
LGTM. But please keep in mind that if your .dcproj does anything unique and interesting, you should consider defining project capabilities to describe these behaviors as well, rather than just grouping them all under this one 'brand' capability.

**Comment by dazhao-msft** [comment]
Thanks for the review. 1.0 just includes the very basic features so it should be enough to have just one capability defined for now. We probably will introduce other capabilities in the future releases.
