### ISSUE TITLE
User settings?

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#163]
I'd like to store some user settings / preferences for my project. These are often stored in a user settings file alongside the project file. Does CPS provide functionality for manipulating user settings / preferences?

**Comment by jviau** [comment]
Yes, CPS supports reading/writing properties to the user file.

You can find the user file properties provider on `IConfiguredProjectServices.UserPropertiesProvider`

You can also use the XAML rule system and specify a data source of "UserFile", these properties will then all be stored/retrieved from the user file.

**Comment by adrianvmsft** [comment]
We are working on a new sample, that stores some debugger properties in the .user file, and uses them later to launch a debugger with the values.

You can take a look at #180. Here are the interesting snippets:
ScriptDebugger.xaml defines RunCommand, RunCommandArguments and RunWorkingDirectory.
Default values are defined in .props.

These properties are used in 2 different places:
- Debug Launch Provider (F5 and Ctrl F5 from Visual Studio)
- The "Run" Target - that can be used from MSBuild - MSBuild /t:Run
  - .user file is imported in .targets for consumption by the .targets file
  ```xml
  <Import Project="$(MSBuildProjectFullPath).user" Condition="Exists('$(MSBuildProjectFullPath).user')" /> 
  ```

**Comment by dazinator** [comment]
Thanks for this btw, was very useful, cheers.
