### ISSUE TITLE
IVsDebuggableProjectCfg and IVsProjectCfgDebugTargetSelection

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#166]
I would like to display a list of custom debug targets. 

Did some research and came acro[ss this interface: IVsProjectCfgDebugTargetSelection](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsprojectcfgdebugtargetselection(v=vs.140).aspx) - which I believe is the extensibility point I am after, but I would like to check - can I implement and register this from within a CPS based project system?  

The docs also pointed to the fact that: 

> This interface is retrieved by a QueryInterface from the project's configuration object that implements IVsDebuggableProjectCfg.

Does CPS implement IVsDebuggableProjectCfg somewhere - and can I participate in this "QueryInterface" to register my own implementations of things?

**Comment by davkean** [comment]
Implement `IDynamicDebugTargetsGenerator`, see: https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileDebugTargetGenerator.cs for an example.

**Comment by dazinator** [comment]
Thank you kindly. I'll give that a try :-)

**Comment by dazinator** [comment]
Hmm - so I tried to implement this, by looking at that implementation above.

I attempted to derive from `ProjectValueDataSourceBase` - but the constructor of that base class wants an `JoinableTaskContextNode`. 

In the sample you linked, it passes `unconfiguredProject.Services` like so:
```
[ImportingConstructor]

        public DebugProfileDebugTargetGenerator(UnconfiguredProject unconfiguredProject, ILaunchSettingsProvider launchSettingProvider)

            : base(unconfiguredProject.Services)

        {

            LaunchSettingProvider = launchSettingProvider;

        }

```

However when I do that, I get compile error:

```
 cannot convert from 'Microsoft.VisualStudio.ProjectSystem.IUnconfiguredProjectServices' to 'Microsoft.VisualStudio.Threading.JoinableTaskContextNode`
```

How do I correctly derive from this base class?

**Comment by dazinator** [comment]
Hmm it looks like that in vs2017, the constructor for `ProjectValueDataSourceBase` has been changed to accept IProjectServices rather than `JoinableTaskContextNode`

**Comment by dazinator** [comment]
Have decided to support vs2017 only for now, as things seem a bit simpler in this area, `JoinableTaskContextNode` threw me.

**Comment by dazinator** [comment]
All working - thanks again @davkean
