### ISSUE TITLE
Support for C++ Project Type

### ISSUE THREAD

**Issue by gprossliner** [Microsoft/VSProjectSystem#168]
Hello!

This may be more a question than an issue. I am wondering if it is possible to create a Project-Type for a C++ environment. It would be a VS integration of the mbed-cli (https://github.com/ARMmbed/mbed-cli).

Are the following things possible:?
- A single project Includes everything starting from a root-directory, not explicitly excluded. So there should be no project-file enumerating all the items.
- It would be nice to use the internal Intelisense / Completion provider of Visual Studio, and not have to roll one by our own.
- Compilation is also done by the cli interface. It just have to call it with some args. So this should be no problem. Is there a kind of dependency to msbuild?
- Debugging is done by a GDB Server. Is it possible to use the MIEngine within the project?

Thank you guys. Any hint would be greatly appreciated!

**Comment by adrianvmsft** [comment]
- CPS added support for [globs](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/globbing_behavior.md) in VS 2017; that feature is used extensively by .Net Core projects, but not by C++. So theoretically it should work, but you may run into issues.
- It's difficult to tell without trying whether the intellisense will work or how accurate it would be
- CPS doesn't build. It invokes the right MSBuild targets (Build, Clean, Rebuild, etc) so as long as your targets to do the right thing, it should be fine
- You can provide a [Debug Launch Provider](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/IDebugLaunchProvider.md) to integrate with custom debuggers
Another thing to keep in mind is that the C++ project implementation in Visual Studio is only partially implemented on top of CPS, so you may run into issues where CPS features may not be available in C++ projects.

Hope this helps,
Adrian

**Comment by gprossliner** [comment]
Thank you for your response. I missed the notification on this thread.

The project structure seems to be working ok. For the other things mentioned, I need some time to work on this.
