### ISSUE TITLE
Globbing with DependentUpon

### ISSUE THREAD

**Issue by aienabled** [Microsoft/VSProjectSystem#169]
I've read this page about globbing in VS 2017 RC https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/globbing_behavior.md and very happy with how everything works. But...

Are there any way of using DependentUpon with globbing?

Currently I have these rules:
```
    <Page Include="**\*.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>

    <Compile Include="**\*.xaml.cs">
      <DependentUpon>*.xaml</DependentUpon>
    </Compile>
```
But it seems DependentUpon is not working this way - solution explorer displays ```Foo.xaml``` and ```Foo.xaml.cs``` as the separate files, but I need ```Foo.xaml.cs``` to be nested in ```Foo.xaml```.
There is a warning generated:
```The parent file, '*.xaml', for file 'Foo.xaml.cs' cannot be found in the project file.```

Regards!

**Comment by aienabled** [comment]
By the way, DependentUpon is applied to my XAML rule (and worked fine in VS2015) https://github.com/Microsoft/VSProjectSystem/blob/b70104c4781749369c995a48f83e64607a0c6594/doc/extensibility/automatic_DependentUpon_wireup.md but it doesn't work with globbing.
Here are the rules I'm using:
```XML
    <ContentType
        Name="PageXaml"
        DisplayName="XAML Page"
        ItemType="Page">
        <NameValuePair Name="DependentFileExtensions" Value=".cs" />
        <NameValuePair Name="DefaultMetadata_SubType" Value="Designer" />
        <NameValuePair Name="DefaultMetadata_Generator" Value="MSBuild:Compile" />
    </ContentType>

    <ItemType Name="Page" DisplayName="XAML Page" />

    <FileExtension Name=".xaml" ContentType="PageXaml" />
```

**Comment by aienabled** [comment]
Ok, I've found a good workaround - added this to the CSPROJ:

```XML
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
```

**Comment by onovotny** [comment]
This pattern may also be useful for T4 templates and their generated output

**Comment by aienabled** [comment]
For those who're also using ReSharper it might be helpful - it seems I've found a bug which is affects only ReSharper - it reports for every named XAML element that the field is already declared - because it looks into the `obj` folder and sees `.xaml.g.cs` files. That's strange because I explicitly removed this folder from the included compile items:
```XML
<-- this not works for ReSharper for some reason -->
<Compile Include="**\*.cs"  />
<Compile Remove="obj\**"  />
```

This fixes the issue:
```XML
<Compile Include="**\*.cs" Exclude="obj\**" />
```

**Comment by aienabled** [comment]
The resulting files globbing code for including `XAML` files with according `.XAML.CS` code-behind files in my case:
```XAML
    <Compile Include="**\*.cs" Exclude=".temp\**" />    
 	<Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>      
    </Compile>
			
    <Page Include="**\*.xaml">
        <Generator>MSBuild:Compile</Generator>
        <SubType>Designer</SubType>      
    </Page>
```

Please note that you need to define `Page` rule to properly process `XAML` files with CPS.

**Comment by adrianvmsft** [comment]
In order to support Depend Upon items in combination with globs, we added a new feature - dynamic depend upon items - the dependency between files is calculated dynamically when project is loaded and doesn't get persisted in the project file.

Documentation is pending, so here is a quick overview:

You can use the existing implementation of IDependentFilesProvider that uses metadata defined in the project items schema to identify dependent files:

```xml
<ContentType
  Name="aaaSourceFile"
  DisplayName="aaa source file"
  ItemType="aaaCompile">
    <ContentType.Metadata>
      <NameValuePair Name="DependentExtensions" Value=".aaa.cs;.aaa.txt" />
    </ContentType.Metadata>
</ContentType>
```
This snippet will make .aaa.cs and .aaa.txt files to be displayed as dependent on .aaa files

For more advanced relationships you can implement a new IDependentFilesProvider.

**Comment by aienabled** [comment]
@adrianvmsft, thanks! I just checked this and it doesn't work for me in the latest VS2017 RC - dependent `.xaml.cs` files are still displayed separately. I'm using this `XAML` rule:
```XAML
<ContentType
        Name="PageXaml"
        DisplayName="XAML Page"
        ItemType="Page">
		<ContentType.Metadata>
			<NameValuePair Name="DependentExtensions" Value=".xaml.cs" />
		</ContentType.Metadata>
    </ContentType>
```

**Comment by adrianvmsft** [comment]
You're right, I forgot to mention that you also need to define the DynamicDependentFile capability. Sorry about that.

Could you try adding the following to your project (e.g. in the .targets file):
```Xml
<ProjectCapability Include="DynamicDependentFile"/>
```

**Comment by aienabled** [comment]
@adrianvmsft, thanks! It works now as expected.
It would be great if you also update the [automatic_DependentUpon_wireup.md](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/automatic_DependentUpon_wireup.md) page  to mention about this new feature.

Regards!

**Comment by adrianvmsft** [comment]
Great! I am glad that it worked!
Updating that page is already on my todo list - I actually pretty much did half of the work replying here :). Once I do that, I will close this issue.
Thanks!

**Comment by adrianvmsft** [comment]
Here is the PR with the documentation update, in case you would like to take a look: #187

**Comment by bdovaz** [comment]
Anyone got this working? I'm able to compile it but I lost intellisense in VS 2017.

This is my csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LanguageTargets>$(MSBuildExtensionsPath)\$(VisualStudioVersion)\Bin\Microsoft.CSharp.targets</LanguageTargets>
    <OutputType>winexe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <DebugType>Full</DebugType>
    <ApplicationIcon>res\ico\icon.ico</ApplicationIcon>
    <OutputTypeEx>winexe</OutputTypeEx>
    <StartupObject />
  </PropertyGroup>

  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">15.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
    <TransformOnBuild>True</TransformOnBuild>
    <TransformOutOfDateOnly>false</TransformOutOfDateOnly>
  </PropertyGroup>

  <Import Project="$(VSToolsPath)\TextTemplating\Microsoft.TextTemplating.targets" />

  <ItemGroup>
    <!-- App.xaml -->
    <ApplicationDefinition Include="App.xaml" SubType="Designer" Generator="MSBuild:UpdateDesignTimeXaml" />

    <!-- XAML elements -->
    <Page Include="**\*.xaml" SubType="Designer" Generator="MSBuild:UpdateDesignTimeXaml" Exclude="App.xaml" />
    <Compile Update="**\*.xaml.cs" SubType="Designer" DependentUpon="%(Filename)" />
    <Compile Include="$(IntermediateOutputPath)**\*.g.cs" Visible="false" />
    <None Include="$(ProjectDir)obj" Visible="false" />

    <!-- Resources -->
    <EmbeddedResource Update="Properties\Resources.resx" Generator="ResXFileCodeGenerator" LastGenOutput="Resources.Designer.cs" />
    <Compile Update="Properties\Resources.Designer.cs" AutoGen="True" DependentUpon="Resources.resx" DesignTime="True" />

    <!-- Settings -->
    <None Update="Properties\Settings.settings" Generator="SettingsSingleFileGenerator" LastGenOutput="Settings.Designer.cs" />
    <Compile Update="Properties\Settings.Designer.cs" AutoGen="True" DependentUpon="Settings.settings" />

    <None Update="App.config">
      <TransformOnBuild>true</TransformOnBuild>
    </None>
    <None Update="App.Debug.config">
      <IsTransformFile>True</IsTransformFile>
    </None>
    <None Update="App.Release.config">
      <IsTransformFile>True</IsTransformFile>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Publish\**" />
    <EmbeddedResource Remove="Publish\**" />
    <None Remove="Publish\**" />
    <Page Remove="Publish\**" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>

  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />
</Project>

**Comment by aienabled** [comment]
@bdovaz I responded there https://github.com/dotnet/project-system/issues/1467#issuecomment-297922937

**Comment by bradphelan** [comment]
Here is a fun example of bad behaviour of globbing and the project system. I have

```
  <ItemGroup>
    <Compile Update="Properties\*.resx.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\*.resx">
      <Generator>I18NReactive</Generator>
      <LastGenOutput>%(Filename).resx.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

```

where I18NReactive is a custom single file generator I wrote. The globbing and dependencies work at first glance.

![image](https://user-images.githubusercontent.com/17650/31270734-d7a58a20-aa85-11e7-9ead-b4ab25038930.png)


Then I right click and select **run custom tool** to regen the ``resx.cs`` file.  And not only does it update the file it **also** updates my csproj file. 👎 so now it is

```
  <ItemGroup>
    <Compile Update="Properties\*.resx.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\*.resx">
      <Generator>I18NReactive</Generator>
      <LastGenOutput>%(Filename).resx.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\lang.resx.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>lang.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\lang.resx">
      <Generator>I18NReactive</Generator>
      <LastGenOutput>lang.resx.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

```
 that's kinda wierd no?

**Comment by bradphelan** [comment]
I made the above comment a new issue at https://github.com/dotnet/project-system/issues/2873

**Comment by Latency** [comment]
Can anybody tell me how to get the designer working again?
Default rule.. automatically does "*.cs", but how do I set the properties of the component via the designer?

```
    <Compile Update="Service.cs">
	    <SubType>Component</SubType>
    </Compile>
```
