### ISSUE TITLE
VS2017 Extensibility Preview - Custom tools not set

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#175]
Created a new project system project using the template.

Noticed on Resources.resx:

![image](https://cloud.githubusercontent.com/assets/3176632/22855767/3b695d66-f07d-11e6-913f-9cbd6f96250a.png)

Shouldn't this have a custom tool set?

![image](https://cloud.githubusercontent.com/assets/3176632/22855775/495f958e-f07d-11e6-805b-e1fbebd4824d.png)

Then added a new rule file.

Noticed the custom tool was set like this:

![image](https://cloud.githubusercontent.com/assets/3176632/22855776/615b52b8-f07d-11e6-9e35-c9bdea6da9ad.png)

I'm not sure this is wrong, but just looked odd because I noticed the other rule files use this custom tool:

MSBuild:GenerateRuleSourceFromXaml

**Comment by adrianvmsft** [comment]
Could you describe the steps you used to add the XAML rule to the project?

If you added a standard XAML file (e.g. one typically used for Windows apps) to the project, you may see that problem.
You should use the item template that comes with VSProjectSystem (that is located under Extensibility/Project System/Xaml Rule). That should set the right properties on the item.

The XAML rule files used by the project system use a custom MSBuild Task that generates some .cs code (that is specific to the project system) based on the content of the file.
That task is defined in the Microsoft.VisualStudio.ProjectSystem.SDK.Tools nuget package (that you can typically find in the packages subfolder).

Resx is slightly different as it is a well known generator in Visual Studio, so it may work even without the right properties set.

**Comment by dazinator** [comment]
I will double check how the xaml rule was added, but it was either via the add new rule item template, or it may have been copied into the folder on disk, and then "included" into the project via solution explorer.

The resources file was created automatically when I created the project, using the extensibility template. The reason I noticed the problem was because there was no strongly typed Resources class being generated, until I set the custom tool on this file manually.

**Comment by adrianvmsft** [comment]
Indeed, adding XAML rules via item templates was adding
```Xml
<Generator>MSBuild:Compile</Generator>
```
That was causing the Custom Tool to be XamlIntelliSenseFileGenerator. (I think it was inheriting some default properties from XAML files).
We made a fix, it should be available in the next version of VS Project System Extensibility.

Thanks!
