### ISSUE TITLE
[Question] - polling on a background thread

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#188]
I am implementing a `IDynamicDebugTargetsGenerator` - where the list of debug targets are IIS websites.
In order to make sure this list is kept up to date, I need to do some monitoring in the background, and I am thinking I'll need to poll IIS, periodically - say every minute.

It would be nice if IIS could actually notify me when a website is added or removed - but I haven't found an API for that yet.

My question is, is there a reccomended way of scheduling / running background polling tasks in VS as part of the VSProjectSystem - or can I just start my own background thread and let it run indefinately? Any relevent docs you could point me at would be most welcomed!

**Comment by adrianvmsft** [comment]
Best place to ask this question would be on the vs-threading repo (CPS uses it). There is also a gitter linked from the main page:
https://github.com/Microsoft/vs-threading

**Comment by dazinator** [comment]
Will do, thanks
