### ISSUE TITLE
[Question] - Targets for BeforeBuild and AfterBuild 

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#190]
Hello!

In standard c# projects you can add the following targets to your project file to execute things before or after a build:

```
<Target Name="BeforeBuild">   

  </Target>
  <Target Name="AfterBuild">
   
  </Target>
```

If i define these in my custom project file:

```
<Target Name="BeforeBuild">
    <Message Text="DnnProjectSystem: BeforeBuild" Importance="high"/>
  </Target>
  <Target Name="AfterBuild">
    <Message Text="DnnProjectSystem: AfterBuild" Importance="high"/>
  </Target>

```

When i build, I don;t see any messages. Those build targets are not fired.

I'm wondering what I need to implement so that msbuild invokes these standard targets when it builds my project.

Along the same lines, a number of nuget packages that extend the build process hook into standard build events using property groups like `BuildDependsOn` and `CleanDependsOn` - i.e a nuget package might add a targets file to my project file, containing:

```

<!-- Hook into the PreBuild, AfterBuild, and AfterClean -->
  <PropertyGroup>
    <BuildDependsOn>
      DoSomething;
      $(BuildDependsOn);
      DoSomethingElse
    </BuildDependsOn>
    <CleanDependsOn>
      $(CleanDependsOn);
      CleanSomething
    </CleanDependsOn>
  </PropertyGroup>


```

However if I import a targets file as above, into my custom project and then build my project, none of those targets are fired. 

I think there must be some top level / standard targets defined somewhere, which msbuild looks for and executes - but I am not sure where to look or what to implement, to get this support.

**Comment by adrianvmsft** [comment]
I think you should digest how this is done in the C# targets and try to match that pattern if feasible.

To do that, you could create a .Net core console project and run from a developer command project from the project folder:

```
msbuild /pp:pp.txt foo.csproj
```
This generates a single file (e.g. pp.txt) that contains an aggregation of all the targets that your project consumes. After that you can search how PreBuild, AfterBuild, etc are hooked up.

You will find:
```xml
  <PropertyGroup xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <BuildDependsOn>
      BeforeBuild;
      CoreBuild;
      AfterBuild
    </BuildDependsOn>
  </PropertyGroup>
  <Target Name="Build" Condition=" '$(_InvalidConfigurationWarning)' != 'true' " DependsOnTargets="$(BuildDependsOn)" Returns="$(TargetPath)" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" />
```

So you could define the `BuildDependsOn` property and specify it as `DependsOnTargets` to your `Build` target.
