### ISSUE TITLE
Project Creation Failed - how to debug?

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#194]
I removed csharp targets from my main project file, and now when my project is created VS just shows this and aborts project creation:

![image](https://cloud.githubusercontent.com/assets/3176632/23284091/6ec3566e-fa21-11e6-8c04-8e74950409c6.png)

My question is, (and perhaps this is the wrong repo for this question, not sure if it should be extendvs) - where can I see some logs to diagnose the problem (i.e the reason why project creation failed) and is there anyway I can debug this?

Cheers

**Comment by adrianvmsft** [comment]
Did it create anything on the disk? Do you have any capabilities defined in your project/targets?
You could also try loading a project you created previously where you replicate the removal of the targets. If it doesn't load, perhaps try building it from MSBuild.

You could try to attach to Visual Studio and catch all exceptions and see if you get any meaningful exceptions.

Other options are to enable the [visual studio log](https://msdn.microsoft.com/en-us/library/ms241272.aspx) and/or the [cps log](https://blogs.msdn.microsoft.com/andrewarnottms/2012/06/07/enable-c-and-javascript-project-system-tracing/).

I did that recently in the Window Script Sample, but don't remember running into this issue.

**Comment by dazinator** [comment]
Ok thank you.
