### ISSUE TITLE
ProjectItem not created on disk when project created.

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#197]
So my project template is installed to the vs experimental instance:

![image](https://cloud.githubusercontent.com/assets/3176632/23343568/86d8c6e4-fc65-11e6-9fee-2c49777af834.png)

In my `VSTempate` file, I have added "manifest.dnn" as a ProjectItem.

```
<?xml version="1.0" encoding="utf-8"?>
<VSTemplate Version="3.0.0" Type="Project" xmlns="http://schemas.microsoft.com/developer/vstemplate/2005" xmlns:sdk="http://schemas.microsoft.com/developer/vstemplate-sdkextension/2010">
  <TemplateData>
    <Name>DNN Extension</Name>
    <Description>A template for creating a DNN Extension.</Description>
    <Icon>DnnProjectSystem.ico</Icon>
    <ProjectType>DnnProjectSystem</ProjectType>
    <RequiredFrameworkVersion>4.0</RequiredFrameworkVersion>
   
    <!--<FrameworkVersion>4.0</FrameworkVersion>-->
    <!--<RequiredFrameworkVersion>4.0</RequiredFrameworkVersion>
    <FrameworkVersion>4.0</FrameworkVersion>-->
    <SortOrder>1</SortOrder>
    <TemplateID>{590fc157-7cfe-4209-a164-b3fdec55aac9}</TemplateID>
    <CreateNewFolder>true</CreateNewFolder>
    <DefaultName>DnnExtension</DefaultName>
    <ProvideDefaultName>true</ProvideDefaultName>
    <PromptForSaveOnCreation>false</PromptForSaveOnCreation>
    <SupportsCodeSeparation>true</SupportsCodeSeparation>
    <AppliesTo>DnnProjectSystem</AppliesTo>
  </TemplateData>
  <TemplateContent>
    <Project File="DnnProjectSystem.dnnproj" ReplaceParameters="true">
      <!-- 
      These are the items which will show up when a new project is created using the custom project system.
      Items referenced in here must also be referenced in the project file.
      -->
      <ProjectItem>Properties\AssemblyInfo.cs</ProjectItem>
      <ProjectItem ReplaceParameters="true" OpenInEditor="true">manifest.dnn</ProjectItem>

      <!--<ProjectItem OpenInEditor="true" ReplaceParameters="true">Program.cs</ProjectItem>-->
    </Project>

  </TemplateContent>
  <WizardExtension>
    <Assembly>NuGet.VisualStudio.Interop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName>NuGet.VisualStudio.TemplateWizard</FullClassName>
  </WizardExtension>
  <WizardData>
    <packages repository="extension"
          repositoryId="DnnProjectSystem.ProjectType..d310c2e3-dc4e-4aab-95cd-f70cba3ecd6f">
      <package id="DnnProjectSystem.BuildTools" version="0.0.1-alpha1" />
      <!--<package id="DnnPackager" version="2.0.6" />-->
    </packages>
  </WizardData>
</VSTemplate>
```

Yet when I create this project:

![image](https://cloud.githubusercontent.com/assets/3176632/23343630/bed5e5f8-fc66-11e6-8547-5fef71ccdd29.png)

The dnn manifest file is not created on disk.

I have an msbuild item entry in my project file for it, and it shows up in solution explorer, with an associated rule file, and its properties window looks good. There are no errors - its simply the file hasn't been created on disk.

Am i missing something here?

**Comment by adrianvmsft** [comment]
Is your file included by a glob?
If you do, make sure your template contains:
```
<CreateInPlace>true</CreateInPlace>
```

Without this flag, the template gets expanded in a temporary location, gets saved and gets copied to the final location. I don't remember exactly the details, but the template engine was expecting items to be explicitly included in the project. This reminds me I should update the globbing doc to mention that issue.

https://github.com/Microsoft/VSProjectSystem/blob/master/samples/WindowsScript/WindowsScript/WindowsScript.ProjectTemplate/WindowsScript.vstemplate

**Comment by dazinator** [comment]
Nope not using globbing. Just a standard msbuild item, with an include attribute!

**Comment by dazinator** [comment]
In the end I started my project system from scratch. I couldn't replicate this problem, so am closing.
