### ISSUE TITLE
ProjectValueDataSourceBase

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#205]
In vs2015, I just wanted to check something about how to implement  `ProjectValueDataSourceBase` 

You have to implement these:

```
 public override Guid DataSourceKey
        {
            get
            {
                throw new NotImplementedException();
            }
        }

        public override IComparable DataSourceVersion
        {
            get
            {
                throw new NotImplementedException();
            }
        }

        public override IReceivableSourceBlock<IProjectVersionedValue<IReadOnlyList<IEnumValue>>> SourceBlock
        {
            get
            {
                throw new NotImplementedException();
            }
        }


```

Am I right in thinking that:

1. The key needs to be constant GUID.
2. The DataSourceVersion needs to be some value that you would increment if the property values you are supplying ever changes?
3. SourceBlock - some safe way of publishing new values?!

For SourceBlock, I think I can study dataflow stuff and look at the VS2017 roslyn implementation of that because I believe that is basically the same in vs2015 and vs2017.

**Comment by adrianvmsft** [comment]
We currently have a documentation pull request in progress that explains many of these concepts.
#199
Please let us know what you think.

**Comment by dazinator** [comment]
This is excellent. Took me a while to wrap my head around the data flow diagram with A B C and D but think I got there in the end. In the diagram, I was trying to work out what the real difference was between C and D, because C can publish when either datasource changes, where as we are saying D can't do that, it can only publish when versions are aligned. I get the concept, but does that mean in an implementation of that diagram C and D would be configured differently in the dataflow? I.e D would use the synclink but C wouldn't?

**Comment by jviau** [comment]
You should still use `SyncLinkTo` for C to guard against A or B changing their implementation. In the current example it wouldn't do much and would publish on every version change, but there is no harm in that. `SyncLinkTo` is mainly beneficial when the different inputs have a non-empty intersection of versions.

**Comment by dazinator** [comment]
Thanks for helping to clarify this, I will close!
