### ISSUE TITLE
[Question] SingleFileGenerator - Export as CPS extensions

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#206]
It seems that single file generators (custom tools) need to be registered with a particular project type guid:

```
 [CodeGeneratorRegistration(typeof(AscxDesignerClassGenerator), "AscxDesignerClassGenerator", "{" + Guids.ProjectTypeGuid + "}", GeneratesDesignTimeSource = true)]

```

So doesn't this eliminate the possibility of exporting a single file generator / custom tool for use with any project that defines a capability?

I'd like to achieve something like this:

ProjectType Foo (for building webforms modules for CMS foo) --> declares "AscxDesigner` capability -> SingleFileGenerator for ascx files is imported.

ProjectType Bar (for building webforms modules for a different CMS) --> declares "AscxDesigner` capability -> SingleFileGenerator for ascx files is imported.

At the moment, because the custom tool has to be registered using a particular project type GUID, I am not sure this is really possible.

**Comment by dazinator** [comment]
The only solution I can think of, is that rather than distibuting the custom tool as a VSIX, I just distribute it as a normal nuget package, containing the single file generator. Then project systems that would want to use it, would reference it, then register it themselves for their own project type guid by doing this:

```
[CodeGeneratorRegistration(typeof(AscxDesignerClassGenerator), "AscxDesignerClassGenerator", "{" + Guids.ProjectTypeGuid + "}", GeneratesDesignTimeSource = true)]
[ProvideBindingPath] 
[ProvideObject(typeof(AscxDesignerClassGenerator))]

```

I think that might work?

**Comment by adrianvmsft** [comment]
In the project type that gets generated by the Project System Extensibility, you have the `ProjectTypeRegistration` attribute (in `MyUnconfiguredProject.cs`) that specifies the project type GUID:

```CSharp
[ProjectTypeRegistration(VsPackage.ProjectTypeGuid, "ProjectType1", "#2", ProjectExtension, Language, resourcePackageGuid: VsPackage.PackageGuid, PossibleProjectExtensions = ProjectExtension, ProjectTemplatesDir = @"..\..\Templates\Projects\MyCustomProject")]
```
The project type Guid as a predefined const in `VsPackage.cs`.

**Comment by dazinator** [comment]
Yeah, thanks - but I know where the project type GUID is :-) haha

This is more about the fact that to register a single file generator, you have to register it with the project type GUID. Therefore if I wanted to publish a reusable single file generator, that others could freely use in their own project systems, how best to achieve that - because I can't know their project guids in advance, so I can't distribute my a file generator as it's own vsix package that others could take a dependency on for example. 

I'm trying to get this to work by publishing a regular nuget package containing the generator class instead. Then a project system that needs the tool would take a dependency on my nuget package, and then add their own registration attribute with their GUID to register the tool for their project type.

I think in theory this should work but for some reason when I try this the tool isn't being registered in the registry. I'll keep working through it though, sure I am making a mistake somewhere!

**Comment by adrianvmsft** [comment]
Project system extensibility does something very similar that what you are looking into for the XAML rule files: nuget package, that delivers a targets file with a custom MSBuild task, that gets run on .XAML rule files to generate C# code based on the content of the .XAML rule content

That logic exits in the `Microsoft.VisualStudio.ProjectSystem.SDK.Tools` nuget package; you can take a look at the .targets file to see how it is connected.

If that doesn't work for you, I collected more information about non-MSBuild single file generators below:
Details about registering Single File Generators
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/registering-single-file-generators

I think you should be able to register it to the projects you would like to support.
I suppose other project type owners could also register your generator with their project type if they would like to use it.

You can find the guids of some well known project types here:
https://msdn.microsoft.com/en-us/library/vslangproj80.vscontextguids.aspx

Also, you can also browse the registry to see what project types are available - I've just sent a PR to explain how to do that: #208

**Comment by dazinator** [comment]
Cheers,

> That logic exits in the Microsoft.VisualStudio.ProjectSystem.SDK.Tools nuget package; you can take a look at the .targets file to see how it is connected

I looked, but I can't get away with the approach used there, as I need the file processing to happen immediately on file save, not on project build. This is why I am having to use a Single File Generator as opposed to an msbuild target. Was interesting to see item types being delivered by nuget package though.

> If that doesn't work for you, I collected more information about non-MSBuild single file generators below:
Details about registering Single File Generators
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/registering-single-file-generators

Thanks. 

>
I think you should be able to register it to the projects you would like to support.
I suppose other project type owners could also register your generator with their project type if they would like to use it.

Yeah i'd like the project type owners to register my generator with their project, think that's easiest.

> Also, you can also browse the registry to see what project types are available - I've just sent a PR to explain how to do that: #208

Thanks. I'll close this issue now as more than enough info to go with.
