### ISSUE TITLE
Generator doesn't show in properties windows when added to script sample

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#210]
In order to see a basic Single File Generator working, I took the windows script sample, and followed [the docs](https://github.com/Microsoft/VSProjectSystem/blob/b70104c4781749369c995a48f83e64607a0c6594/doc/scenario/add_single_file_generator.md) to add a basic `FooGenerator`.

So here is my branch ~- but it doesn't appear to work~: https://github.com/dazinator/VSProjectSystem/tree/issue-single-file-generator

And here is my commit: https://github.com/dazinator/VSProjectSystem/commit/bdc6e47b5ba98dee962ae9984de30403f14bc053

The Generator property doesn't show up in the properties window, despite it being added to the rule file:

![image](https://cloud.githubusercontent.com/assets/3176632/23836652/92ed1cdc-0773-11e7-82b4-839d1e10d504.png)

To run the sample, just clone it, nuget restore, then you'll probably have to restart vs due to the msbuild task version issue. Perhaps you can spot something I have missed or have not followed correctly from the docs?

**Comment by dazinator** [comment]
Turns out the issue is just that Generator doesn't show in the properties window. If you edit the proj file to set the generator like this:

```csharp

  <ItemGroup>
    <Script Include="**\*.js">
      <Generator>FooGenerator</Generator>
    </Script>
    <Script Include="**\*.vbs">
      <Generator>FooGenerator</Generator>
    </Script>
  </ItemGroup>

```

The generator does work.

**Comment by aienabled** [comment]
Instead of 
```
   <Script Include="**\*.js">
      <Generator>FooGenerator</Generator>
    </Script>
```
You could try updating ProjectItemsSchema for "Script" item to set generator field default value (`DefaultMetadata_Generator`). I mean something like this:
```
  <ContentType
        Name="Script"
        DisplayName="Script"
        ItemType="Script">
	    <NameValuePair Name="DefaultMetadata_Generator" Value="FooGenerator" />
    </ContentType>
```
So it will work in VS2015 as well.

**Comment by dazinator** [comment]
Thanks I'll see if that makes a difference. I would have thought generator property should be displaying in the properties window though, with or without that, but let's see!

**Comment by dazinator** [comment]
Sadly it's as I thought. Setting the default generator in `ProjectItemsSchema` doesn't fix the issue of the generator property not showing up in properties window. The generator is functional though, but just doesn't show in properties..

It seems adding the property here to this rule file isn't enough: https://github.com/dazinator/VSProjectSystem/commit/bdc6e47b5ba98dee962ae9984de30403f14bc053#diff-079745da7dcc0e57b26686f65d0b97a8R13
 
What am I missing?

**Comment by dazinator** [comment]
Ok so I found the reason.

There is a `script.xaml` rule, and a `script.browseobject.xaml` rule. In order to add a property to the properties window, it appears you have to add it to the latter one - where as I had added it to the former.

These two xaml rule files seem to be very similar, except one is tied to a context of `File` and the other is tied to a context of `BrowseObject` - which I am assuming is the context of the properties window?

```
    <PropertyPageSchema Include="$(MSBuildThisFileDirectory)Rules\script.xaml;">
      <Context>File</Context>
    </PropertyPageSchema>
    <PropertyPageSchema Include="$(MSBuildThisFileDirectory)Rules\script.browseobject.xaml;">
      <Context>BrowseObject</Context>
    </PropertyPageSchema>

```

This makes me wonder what context "File" means. I am struggling to think why there isn't just a single xaml rule file - is it best practice to have seperate rule files for seperate contexts?

**Comment by dazinator** [comment]
Closing this and I'll raise a seperate issue Re docs.
