### ISSUE TITLE
[Question] - Displaying a progress UI

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#222]
Hello,

I have a custom `DebugLaunchProvider` which needs to perform some tasks that can take a short while.. Things like:

1. It needs to check the build is up to date, and if not, do a build.
2. It needs to deploy the latest build output to another process.
3. It then proceeds to attach the debugger to the external process

I am pretty new to VS development, and I am wondering what the correct way to develop and display some sort of progress UI whilst these things are ongoing? Is there a CPS way of displaying a generic progress UI?

Any guidance much appreciated.

Thank you.

**Comment by wjk** [comment]
@dazinator I would recommend using the [`IVsThreadedWaitDialog` interface](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsthreadedwaitdialog.aspx). This is the interface that VS itself uses to display progress dialogs. It is also used in other open-source project systems, which is how I found out about it in the first place. Unfortunately, the best example of how it should be used is within the R Tools' project system, which itself is a complicated piece of code. [Here's a direct link to the appropriate file.](https://github.com/Microsoft/RTVS/blob/master/src/Package/Impl/Shell/Services/VsProgressDialog.cs) Hope this helps!

**Comment by dazinator** [comment]
Thank you! I'll give that a go :-)
