### ISSUE TITLE
Setup an IDebugLaunchProvider for a CSharp project

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/VSProjectSystem#225]
I would like to be able to specify a debugger for a CSharp project.
This is for a custom project type that is using csproj as the extension. So it's kind of a project sub type.

**Comment by adrianvmsft** [comment]
This page contain imformation about IDebugLaunchProvider:
https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/IDebugLaunchProvider.md

You can take a look on how we hook up the script debugger for the Windows Script sample:
https://github.com/Microsoft/VSProjectSystem/blob/master/samples/WindowsScript/WindowsScript/WindowsScript.ProjectType/ScriptDebuggerLaunchProvider.cs

**Comment by josesimoes** [comment]
I've managed to add a debugger only after changing the project extension from csproj to something else.
I guess that the extension is "forcing" it to retain behaviours/features of a standard csproj

**Comment by dazinator** [comment]
Sounds familiar. I remember digging into the target files once (I believe microsoft common props / targets) and found there are some conditions in there that detect .csproj and .vbproj file extensions and include some special capabilities. So simply using those file extensions in conjunction with common props / targets means you get additional capabilities that you wouldnt get if you used a different file extension with the same targets / imports. Doesnt make sense to me, and I did raise an issue somewhere but I think it was largely ignored.

**Comment by adrianvmsft** [comment]
Thanks for posting your findings!

Indeed, there are some capabilities that get added based on the project extension. You can do that via the ProjectTypeRegistration attribute (where you can specify an initial set of capabilities).
That allows detecting capabilities early, without having to fully evaluate the project, so it can start components early.
Also, it helps prevent some project reload issues that can happen when capabilities appear later (when implementation doesn't fully support dynamic capabilities). You can refer to [this change](https://github.com/dotnet/project-system/pull/1141) in the dotnet project system for more details.
Unfortunately, that can cause conflicts when using the same project extension.
