### ISSUE TITLE
Using Microsoft.VisualStudio.ProjectSystem with VS2015 results in file not found Microsoft.VisualStudio.Threading 15.0.0

### ISSUE THREAD

**Issue by conniey** [Microsoft/VSProjectSystem#227]
I installed the Microsoft.VisualStudio.ProjectSystem 15.0.751 NuGet package for my VSIX... however, at runtime, I get an error about not being able to locate Microsoft.VisualStudio.Threading 15.0.0. The lowest released version of Microsoft.VisualStudioProject system still depends on Microsoft.VisualStudio.Threading 15.0. Is there a package I can use that will work on VS2015 and VS2017?

The packages for VS2015 defined in [Breaking Changes Visual Studio Next](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/breaking_changes_visual_studio_next.md) are also not found.
* Microsoft.VisualStudio.ProjectSystem.v14Only
* Microsoft.VisualStudio.ProjectSystem.VS.v14Only

**Comment by MikhailArkhipov** [comment]
You need different reference for 2015. Obviously 15.* only works in 2017. We maintain different set of references in

https://github.com/Microsoft/RTVS/tree/Release/1_0/src/ProjectSystem/Impl
https://github.com/Microsoft/RTVS/tree/Release/1_0/src/Package/Impl

```
 "Microsoft.VisualStudio.Threading": "14.1.131",
 "Microsoft.VisualStudio.ProjectSystem": "14.1.170-pre",
 "Microsoft.VisualStudio.ProjectSystem.SDK.Tools": "14.1.170-pre",
```

**Comment by conniey** [comment]
/facepalm. Thanks! I had the "Show prerelease options" off in my NuGet manager. :(
