### ISSUE TITLE
IVsTaskList must be installed for this feature to work 

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#230]
I am attempting to add some messages to the errors window from within my `DebugLaunchProvider`.

When I do this:

```
 ThreadHelper.JoinableTaskFactory.Run(async delegate
            {
                await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();

                _errorListProvider = new Microsoft.VisualStudio.Shell.ErrorListProvider(this.ServiceProvider);
                _errorListProvider.ProviderName = "Dnn";
                _errorListProvider.ProviderGuid = Guid.Parse("365ad42c-264f-4b02-9cde-6c72d6505cb0");
                _errorListProvider.Show();

                var newError = new Microsoft.VisualStudio.Shell.ErrorTask();
                newError.Category = TaskCategory.BuildCompile;
                newError.ErrorCategory = TaskErrorCategory.Message;
                newError.Text = "Hi";
                _errorListProvider.Tasks.Add(newError);

                     });
```

I get an exception stating: 

```
The service 'Microsoft.VisualStudio.Shell.Interop.IVsTaskList' must be installed for this feature to work.  Ensure that this service is available
```
Do I have to include some other dependency or sku / package in my vsix manifest in order to use the errors window?

**Comment by dazinator** [comment]
It turns out, that creating the `ErrorListProvider` directly within the `ImportingConstructor` of my `DebugLaunchProvider` caused this problem. I am assuming that at this point, the `ServiceProvider` that's accessible isn't able to resolve required services..

**Comment by dazinator** [comment]
After adding an error to my `ErrorListProvider`, and calling `Show` (and I have also tried `Refresh`) it takes 1-2 minutes for the error to appear in the Errors window. I am not sure why there is such a delay?

**Comment by jviau** [comment]
@dazinator if that code above is in your `ImportingConstructor` you should move that out. Querying COM services, requiring the UI thread, or performing `JTF.Run` during MEF composition will cause deadlocks. I suggest implementing `OnceInitializedOnceDisposedAsync` and lazy-initializing your `ErrorListProvider`.

**Comment by jviau** [comment]
The error list not showing up is a VSSDK issue, you can try asking here: [https://gitter.im/Microsoft/extendvs](https://gitter.im/Microsoft/extendvs)

**Comment by dazinator** [comment]
@jviau - thank you!
