### ISSUE TITLE
Successive build doesn't skip when buidld is up-to-date

### ISSUE THREAD

**Issue by k-glushko** [Microsoft/VSProjectSystem#231]
When I do two successive builds in **VS2017**, the second build is very fast, because VS detects that there are no changes in the source files.

When I do the same in **VS2017 with CPS**, the second build rebuilds all the solution, which takes a long time.

Tested with a Console App and UWP.

**Comment by adrianvmsft** [comment]
I think we need more details to understand what is going on - What kind of project are you using? Is it C#, or JScript?
Regarding C# - CPS is currently only enabled for .Net Core projects, so I am trying to understand how you use it for Console App or UWP (unless it is Javascript?)

**Comment by k-glushko** [comment]
I have used that link: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/scenario/turn_on_cps_for_csharp_vb_project.md

After changing the guid and repening the project, I see the "Dependencies" node instead of "Reference" in the Solution Explorer. By that I can understand project is using CPS now.

I use a simple Console App.

**Comment by jviau** [comment]
You probably want to discuss this on the [.net project system repo](https://github.com/dotnet/project-system). I believe they only recently added an up-to-date checker, which should be available in 15.3.
