### ISSUE TITLE
IDeployProvider not showing Deploy option on project

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/VSProjectSystem#232]
Hi,

I'm working on a project system where I've added a Deploy Provider (from the Solution File - New).
Apart from replacing AppliesTo with the project unique capability string I haven't changed anything else.
When launching the VS experimental instance and creating a new project I can not see the Deploy option neither on Solution or Project.

Any hints on how to debug this would be appreciated.

**Comment by adrianvmsft** [comment]
Here are some things to try:
- Have you tried right click on the project in the solution explorer?
- Try a clean rebuild of your project; I noticed in the past issues where VS SDK failed to update the extension when using incremental build
- Try setting breakpoints in your code - do they get hit?

**Comment by josesimoes** [comment]
I guess that this is somehow related with #225. After changing the project extension I could see the deploy option available.

**Comment by adrianvmsft** [comment]
Indeed, if you reuse an existing project extension, you risk getting interferences with other projects as there are capabilities that get defined based on the extension.
You should use your own project file extension, unless you want to add features to the existing .net core project implementation.

**Comment by adrianvmsft** [comment]
I updated #225 with more information on why reusing the same project extension can be problematic.
