### ISSUE TITLE
Xaml Rules compilation stops working when adding WPF Xaml pages

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/VSProjectSystem#234]
I'm trying to reach the TargetPath property for a project on the DeployProvider.

1) can't use `Properties.GetConfigurationGeneralPropertiesAsync()` because the build fails. 
Actually there are no errors listed, I can only see this on the build output window. The partial class is there and exists on the obj folder. 

2) Trying to use the dereferenced property fails because types are missing:
`(new System.Threading.Tasks.SystemThreadingTasks_FutureDebugView<Microsoft.Build.Evaluation.Project>(((Microsoft.VisualStudio.ProjectSystem.ConfiguredProjectImpl)Properties.ConfiguredProject).MSBuildProject).Result).AllEvaluatedProperties["TargetPath"]`

**Comment by adrianvmsft** [comment]
Do you have by any chances any WPF xaml files in the same project?

**Comment by josesimoes** [comment]
Yes I do. There is a ToolWindow that hosts a WPF page.

**Comment by adrianvmsft** [comment]
This issue is now fixed in [Microsoft.VisualStudio.ProjectSystem.SDK.Tools 15.3.224](https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem.SDK.Tools/15.3.224)

In order to apply the fix, you will need to upgrade the nuget package used by your project to that version.
