### ISSUE TITLE
Showing a dialog after solution load

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#236]
My project system is progressing nicely, but now I'd like to get a money making screen into it! (I'm sorry.. its terrible, i know).

Basically once a solution is fully loaded, and my project system has been initialised, Id like to check fot a licence and then prompt the user for a licence key if the check fails, My question is, how does one go about launching a modal UI from a CPS project system after solution load?

**Comment by ceztko** [comment]
You may try [this](https://stackoverflow.com/questions/40608094/wpf-modal-window-in-visual-studio-extension-blocking-input) plus events in [IVsSolutionEvents3](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivssolutionevents3.aspx) or [SolutionEvents](https://msdn.microsoft.com/en-us/library/envdte.solutionevents.aspx)

**Comment by dazinator** [comment]
Thank you, I'll give that a go :-)
