### ISSUE TITLE
Add reference.. the given key was not present in the dictionary

### ISSUE THREAD

**Issue by zivkan** [Microsoft/VSProjectSystem#245]
## Repro Steps

1. Clone this repo and open `samples\WindowsScript\WindowsScript.sln`
2. Edit `samples\WindowsScript\WindowsScript\WindowsScript.ProjectType\BuildSystem\DeployedBuildSystem\WindowsScript.targets` and add the following project capabilities: `DependenciesTree`, `ProjectReferences`, `AssemblyReferences`.
3. "run" the project to start the experimental instance of VS with the project system
4. In the experimental instance, open `samples\WindowsScript\WindowsScript\WindowsScript.ProjectTemplate\WindowsScript.wsproj`
5. In Solution Explorer, right click on Dependencies and select "Add reference"

## Expected Behaviour

I expect the dialog to add project references to appear.

## Actual Behaviour

Error message box with the following message:
The given key was not present in the dictionary.

## Extra Info

Using the [project capabilities doco](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/project_capabilities.md) and some experimentation, I found that to add project references, I need to add the `DependenciesTree` and `ProjectReferences` capabilities. My project system's build tools are in a nuget package, so following [this doco](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/project-system-support) I also added `AssemblyReferences` and two other capabilities. However, as reported the add references menu item now just shows an exception message.

**Comment by adrianvmsft** [comment]
I took a look at the code, CPS is expecting to find a rule with the name "ResolvedAssemblyReference".
You can find an example in the history of the windows script sample - in particular this [commit](https://github.com/Microsoft/VSProjectSystem/commit/668fb437ad12b6deae505c63b1177bf89150a4d3).
That commit shows the difference between the old style project types that were being generated by the project system extensibility (that were more comprehensive but were coliding with the new .Net core projects) and the new windows script sample (that is less comprehensive but more isolated).

Please note that the DataSource points to an MSBuild target that you need in the targets file:

```xml
<Rule
    Name="ResolvedAssemblyReference"
    DisplayName="Resolved Assembly Reference"
    PageTemplate="generic"
    Description="Resolved reference"
    xmlns="http://schemas.microsoft.com/build/2009/properties">
    <Rule.DataSource>
        <DataSource Persistence="ResolvedReference" ItemType="Reference" HasConfigurationCondition="False" 
                    SourceType="TargetResults" MSBuildTarget="ResolveAssemblyReferencesDesignTime" />
    </Rule.DataSource>
...
```
Hope this helps.
Thanks,
Adrian

**Comment by adrianvmsft** [comment]
For a more up-to-date version of the rule file, you can take a look at the roslyn project system repo [here](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ResolvedAssemblyReference.xaml)

**Comment by zivkan** [comment]
Thanks Adrian, I added both `ResolvedAssemblyReference.xaml` and `ResolvedProjectReference.xaml`. I can now see the add references dialog.

I didn't explain in my first post, but I want to be able to add references to .NET projects from my not .NET project (the reference represents a dependency that needs to be zipped up in preparation for deployment). When trying to add the reference, I get this message:

> Confirm unsupported reference(s)
> 
> One or more of the selected items is not a valid reference for this type of project.  Do you want to continue and add all the references anyway?

If I click ok, the .wsproj file gets a `<ProjectReference` item, but the References folder doesn't show the reference. And if I go back to the add references dialog, the project is not checked, meaning I can't uncheck it to remove the reference.

Would you like me to close this, and open a new issue?

**Comment by adrianvmsft** [comment]
I took a look at your sample project and the error message you are seeing is caused by the Reference Manager dialog that does some checks to detect if the project can be referenced.

The particular check that fails expects the referencing project (WindowsScript1) to use a higher or equal framework version than the referenced project (ClassLibary1).

The check fails because:
- ClassLibrary1 is 4.6.1 (which I think is expected)
- WindowsScript1 is considered to be 4.0 - which is lower than 4.6.1. 

This is done by evaluating the msbuild property `TargetFrameworkMoniker` which for WindowsScript1 returns `.NETFramework,Version=v4.0`. I took a look using the msbuild preprocessor (`msbuild /pp:pp.xml`) and this is the default value that gets set in `Microsoft.Common.CurrentVersion.targets`).

I set this property in the windows script and that avoids the validation issue
```xml
<TargetFrameworkMoniker>.NETFramework,Version=v4.6.1</TargetFrameworkMoniker>
```
Unfortunately that still doesn't solve the project reference not being checked the second time you open the dialog. Could you please file a separate issue for that?

**Comment by zivkan** [comment]
Thanks again. I really appreciate your help.

I tried to be daring and added `<TargetFrameworkMoniker>.NETFramework,Version=v9.9.9</TargetFrameworkMoniker>`, so that anyone using the project system won't need to update their projects if new versions of .NET come out. Seems to work so far, but I won't be surprised if it causes a problem at some point.

**Comment by adrianvmsft** [comment]
That could cause projects if a regular .Net project (e.g. using 4.6.1) tries to reference your project. Not sure if that is a valid scenario in your case.
