### ISSUE TITLE
IDeployProvider not working on 15.3

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/VSProjectSystem#247]
I've update the Project System NuGets on a VS extension project to the latest available version and now the "Deploy" option is not showing anymore on my projects. 
Has this provider changed?

**Comment by adrianvmsft** [comment]
I took a look through code changes, I didn't find any changes around deploy providers. However, there were some significant changes in 15.3 so regressions are possible.
Could you try to see if you can repro this issue with a brand new project type and add a deploy provider using the item template?
Nuget packages themselves typically shouldn't cause such issues, as they are only used at build time. At runtime, it always uses the CPS binaries that are shipped with Visual Studio. Did you upgrade VS to Update 3?
Other things to try:
- run devenv.exe /updateconfiguration from an admin command prompt to make sure the MEF cache is up to date
- is your extension based on the previous C#-like project type that Project System Extensibility used to create in VS 2015? (If yes, a possible cause could be changes withing roslyn project system used by .Net core projects).

Hope this helps,
Adrian

**Comment by josesimoes** [comment]
Adrian: thanks for the prompt reply and suggestions! 😃 

I've been digging this deeper and here's what I've found.
- I've reverted the project and start updating the NuGet packages one by one.
- To be able to test this I added a static constructor to `static DeployProvider() { }` and put a breakpoint there. Plus I also added a breakpoint to `public bool IsDeploySupported`.

When loading the project and right click on the project node both breakpoints are hit and the "Deploy" option shows on the context menu.

As soon as System.Composition is updated from 1.0.31 to 1.1.0 and I right click on the project node I can see that the static constructor breakpoint is hit but the one in IsDeploySupported is not anymore.

I'm not sure exactly if it's the  System.Composition or one of the packages that it depends on that causes this, but it's easily reproducible following the above.
My guess is that, for some reason, the IsDeploySupported is not being checked anymore.

And yes, I'm running VisualStudio.15.Release/15.3.3+26730.12.

**Comment by adrianvmsft** [comment]
@AArnott and @AlexEyler - does this issue ring any bells?

I wasn't able to repro this issue with a vanilla project type - after adding nuget reference to System.Composition 1.0.31 and upgrading to 1.1.0 - Deploy worked fine in both cases.

Note that default vanilla project type doesn't reference System.Composition package; it only references the default System.ComponentModel.Composition.dll assembly.

@josesimoes I enlisted in the nanoframework/nf-Visual-Studio-extension repo you linked about, it compiled fine, but when I try to create a new Visual C#/nanoFramework/Blank Application (nanoFramework) I get a solution + empty project folder and the following error mesage:

"Project file is incomplete. Expected imports are missing."

Is that expected? Am I missing anything? (I am using a slightly newer version of VS so that could be a possible reason).

**Comment by AArnott** [comment]
Use of `System.Composition` should be fine, but you'd probably want to add the `[Shared]` attribute alongside your `[Export]` attribute, and you might need to specify a sharing boundary as well, I don't recall. 

Have you looked at the MEF error log from `%localappdata%\microsoft\visualstudio\15.0_xxxxxx\ComponentModelCache\Microsoft.VisualStudio.Default.err` to see if your MEF part is being rejected for some reason?

**Comment by josesimoes** [comment]
@adrianvmsft interesting that you get that 
> "Project file is incomplete. Expected imports are missing."

I dont' have any issues with it. The latest build of the VSIX is here:
https://github.com/nanoframework/nf-Visual-Studio-extension/releases/tag/untagged-10a53ca9db83b4fff8fb

And here's a screenshot of the expected outcome:
![2017-09-09_11-40-46](https://user-images.githubusercontent.com/1881520/30239409-e1c4c184-9553-11e7-97b6-06e610c3303e.png)

**Comment by josesimoes** [comment]
After a reinstall of the tools, resetting the experimental instance and updating the NuGet packages one by one, I can confirm that I don't see this issue anymore. 

Thank you all for your time, tips and advice! 😃
