### ISSUE TITLE
NuGet Package from new .csproj - Summary/Title Tag missing

### ISSUE THREAD

**Issue by mishra14** [Microsoft/VSProjectSystem#258]
_From @robertmuehsig on October 25, 2017 21:11_

We are using the new .csproj and the integrated NuGet package building feature and I was wondering why I can't specify "Summary" and "Title" within Visual Studio?

When I upload the produced package to nuget.org, a title and summary field is shown without any input and the summary seems kind of important, because it is related to search?!

![image](https://user-images.githubusercontent.com/756703/32023471-8efecb70-b9d9-11e7-868c-4aa52fb10ac1.png)

Repo steps:
* Create new csproj
* fill out some package details
* upload produced package to nuget.org via the Web UI

I guess this is by design, but then the NuGet Gallery should render the fields differently.

_Copied from original issue: NuGet/Home#6102_

**Comment by mishra14** [comment]
_From @robertmuehsig on October 27, 2017 5:34_

Is this part OSS and are PRs possible/welcome?

**Comment by mishra14** [comment]
@robertmuehsig this UI page is not owned by NuGet. I will move your bug to a better repo.

**Comment by adrianvmsft** [comment]
I think you should open this issue on the [dotnet project system github](https://github.com/dotnet/project-system). That is where the implementation of the .net core project system lives.

**Comment by mishra14** [comment]
This issue was moved to dotnet/project-system#2937
