### ISSUE TITLE
[Question] Enable and Add Property Page to Project Designer

### ISSUE THREAD

**Issue by rishabhkhanna** [Microsoft/VSProjectSystem#272]
Hello,

I was able to add a boiler plate property page using the XAML Rule item template to the property pages window.

![image](https://user-images.githubusercontent.com/17361915/39076379-c79ddf1e-44af-11e8-92a2-c580ef45825d.png)

I'm wondering if it is possible to add a property page to the Project Designer instead? For example, add another tab on the left pane similar to the VSIX tab.

![image](https://user-images.githubusercontent.com/17361915/39076408-ec9f0324-44af-11e8-935f-8795c6bfb310.png)

Currently, when I access the Properties window (Right Click Project Node -> Properties) of a project that was created with a template that I created with the Project Type template; the Properties window looks like the first screenshot. Is there some way to use the Project Designer interface instead?

Thanks

**Comment by jp2masa** [comment]
First, you need to create an `IPropertyPage` implementation, which is the project designer page. Then you need to create an implementation of `IVsProjectDesignerPageProvider` (it needs to be exported), which provides the property page metadata for the `IPropertyPage` implementation. Finally, you need to add `[ProvideObject(typeof(MyPropertyPageImpl))]` (replace `MyPropertyPageImpl` with the name of the `IPropertyPage` implementation) to the VS package class.

I created an implementation of project designer pages some time ago, in case you're interested: VSPropertyPages.sln in https://github.com/CosmosOS/XSharp

**Comment by jviau** [comment]
The AppDesigner is owned by [dotnet/project-system](https://github.com/dotnet/project-system). I am not sure if it is possible it get it working on your own project type, but I know it is possible to add new pages to it when extending the .netcore project system.
