### ISSUE TITLE
Display Name for Installed Template

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/VSProjectSystem#28]
What do you modify in the Project Type project to display within the New Project > Installed Templates?  This would be compared to the Visual C# template.  As an example, what if I wanted a multiple word project type (called My Boo)?  So what file and item do you modify to display New Project > Installed Templates > My Boo?

**Comment by adrianvmsft** [comment]
When you create the project type for the first time, you can specify the Display Name value.
After you have already created your project type, you can modify the template that was generated by default (e.g. ProjectType1.ProjectTemplate). Take a look at the .vstemplate file, it has properties for the name of the template, description, etc. You can find more information here: https://msdn.microsoft.com/en-us/library/vstudio/hy7dh5te(v=vs.140).aspx

**Comment by shaggygi** [comment]
@adrianvmsft Thanks for the response.  This helped me understand where the info comes from for future use, but I was trying to figure out how to set the display name for the installed template type (forgive me for not being detailed).  

As an example, let's say I create a new Project Type named BooAgain with the following parameters.
Display Name: Boo Again
Project file extension: booagainproj
Default namespace: BooAgain

The above info will create an installed template called BooAgain with a template item called Boo Again Project.  I want the installed template on the left side to be two words "Boo Again".

As another example, use the Visual C# installed template.  This is two words, but all I can find is CSharp.  I'm wondering if there is another file/location that maps out the project type to a display name for the installed templates?

Thanks again.

**Comment by adrianvmsft** [comment]
If localization is not important in your case, you can achieve this by making the following changes:
1. ProjectType project: MyUnconfiguredProject.cs - update the value of the Language field
2. ProjectTemplate project: Edit the .vstemplate file and update the value of ProjectType to the same value (otherwise the template won't show up)
You may need to rebuild instead of build to see these changes.

Hope this helps,
Adrian

**Comment by shaggygi** [comment]
Thanks @adrianvmsft  that did the trick.  I think the variable 'Language' is a little odd and why it does not use ProjectType instead for both.  I guess there are reasons from the early days it was designed.

This was more of a question instead of issue, so please go ahead and close out.

Thanks again.

**Comment by adrianvmsft** [comment]
You're welcome!
I agree that the they are somehow inconsistent.
Please let us know if you run into any issues when using space as language/project type.
Thanks,
Adrian
