### ISSUE TITLE
Adding Item Templates for Specific Folders in Project

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/VSProjectSystem#30]
Let's say I have a few folders added with a new Project Type project.  As an example, it includes One, Two and Three.  Is there a way to only show specific types of items templates to be added within a specific folder?  A further detailed example... let's say the user right-clicked the One folder > Add > New Item...  Within the Add New Item dialog, there would be specific templates that could be added (e.g. One.cs).  And if the user did the same for Two folder, it would show a different list of items that could be added (e.g. Two.py).  TIA

**Comment by AArnott** [comment]
No support for folder-specific item template filtering exists in VS2015. I've created a user story (1185119) in our internal database to track this though so that in the future we may add it.

**Comment by shaggygi** [comment]
Thanks for adding to backlog.  Hopefully it will be included in future
release :)
