### ISSUE TITLE
Consistent Project Capitalization

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/VSProjectSystem#31]
The capitalization for the various item templates are not consistent.  As an example, there is one for Custom Debugger Extension and one for Project Deploy extension.  The capitalization for word 'extension' is different.

**Comment by adrianvmsft** [comment]
Good catch! Thanks for reporting it!

**Comment by adrianvmsft** [comment]
I fixed this issue, it should show up in the next release. Thanks!

**Comment by shaggygi** [comment]
Thanks for the update.  I noticed only seeing the project documents on GitHub.  Is it planned to release the source, as well?  Just curious :)

**Comment by AArnott** [comment]
@shaggygi  We'd certainly like to see that, but we can't say when or if at this point.

**Comment by shaggygi** [comment]
I just downloaded the new bits (6/17/15 release) and noticed the capitalization was updated, but not consistent with other types of projects.  I believe the word 'extension' should be capitalized.  As an example, the item templates should be 'Project Deploy Extension', 'Custom Debugger Extension', etc.

Sorry being too picky on this issue :)
