### ISSUE TITLE
Supporting the DependenciesTree capability

### ISSUE THREAD

**Issue by MEikermann** [microsoft/VSProjectSystem#316]
I'd like to support project to project references in my custom project. By adding ReferenceManagerProjects, ProjectReferences, and DependenciesTree capabilities I can add ProjectReferences and actually see them in the SolutionExplorer. Unfortunately the project references are marked as unresolved. Is there any documentation on what a project system needs to provide in order to support the DependenciesTree capability?

**Comment by drewnoakes** [comment]
No documentation, but the answer here is that you need to ensure the design-time build returns `ResolvedProjectReference` items. In general each dependency type has an unresolved form from evaluation (i.e. `ProjectReference`, `PackageReference`, ...) and a resolved form from the design-time build (i.e. `ResolvedProjectReference`, `ResolvedPackageReference`, ...).

In the absence of a resolved item being available, the item will be marked as unresolved in the tree.
