### ISSUE TITLE
"UnitTestContainer" project capability does not work

### ISSUE THREAD

**Issue by KristianJakubik** [microsoft/VSProjectSystem#328]
I've looked into the list of all [Project Capabilities](https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/project_capabilities.md) and one of the listed capability is with name `UnitTestContainer`. When I use it in my .csproj, it is not being recognized. I've tried to replaced capability with `TestContainer` and it worked just fine.

Therefore I suppose that `UnitTestContainer` should be renamed to just `TestContainer`.
If so, can I create PR?

**Comment by drewnoakes** [comment]
I searched an internal code index for usages of `UnitTestContainer` and found only one usage, in Roslyn:

https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/eng/targets/Imports.targets#L42-L45

I tested a few freshly instantiated unit test project templates (xUnit, MSTest, NUnit) with:

```xml
<ProjectCapability Include="DiagnoseCapabilities" />
```

They all have capability `TestContainer` and none have `UnitTestContainer`. I agree this seems like a valid change.

**Comment by drewnoakes** [comment]
For the Roslyn case, I've filed https://github.com/dotnet/roslyn/pull/41334 and am following up internally.
