### ISSUE TITLE
How to Hide PowerShell Related Items in Project Type Project

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/VSProjectSystem#35]
When creating a CPS Project Type project and running in VS hive, there is a PowerShell installed template and a few related item templates to select.  This is also the same when right-clicking the project to add new item.

Is there a way to hide the PowerShell items in your Project Type project?  If so, any docs/steps to do so?

Thanks

**Comment by AArnott** [comment]
Item templates can choose to apply to projects based on capabilities and the owner of the powershell templates has decided that they apply to *all* project types. Projects can't remove them.
But I'll try to find the owner of the powershell item templates and pass along the feedback that you wish they weren't so aggressive in appearing everywhere.

**Comment by shaggygi** [comment]
Thanks for providing the feedback to PowerShell team.  Now that you mentioned you can make your item templates show up everywhere, what would you have to add in order to do that?

**Comment by AArnott** [comment]
Item templates may add the [AppliesTo](https://msdn.microsoft.com/en-us/library/dn497698.aspx?f=255&MSPPError=-2147217396) tag to their .vstemplate file to indicate which projects they should apply to.
