### ISSUE TITLE
Microsoft.VisualStudio.ProjectSystem.VS not found on nuget.org

### ISSUE THREAD

**Issue by reduckted** [microsoft/VSProjectSystem#375]
`Microsoft.VisualStudio.ProjectSystem.SDK` v17.9.380 was published to [nuget.org](https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem.SDK) a few days ago. It has a dependency on `Microsoft.VisualStudio.ProjectSystem.VS`, but that package has not been published on nuget.org.

![image](https://github.com/microsoft/VSProjectSystem/assets/10321525/a6803bd6-982e-48d2-a5fd-6676eceea50a)

**Comment by adrianvmsft** [comment]
We did run into an issue publishing the nuget packages that was addressed today. The issue should be fixed now.
Thank you for reporting this issue.

**Comment by adrianvmsft** [comment]
Closing this item

**Comment by adrianvmsft** [comment]
Closing this item

**Comment by reduckted** [comment]
I can confirm that `Microsoft.VisualStudio.ProjectSystem.VS` can now be installed. Thanks!
