### ISSUE TITLE
Problem with IDynamicEnumValuesProvider not picked up in VS2015

### ISSUE THREAD

**Issue by phofman** [Microsoft/VSProjectSystem#39]
I tried to follow the [VS2013 to VS2015 porting instruction](/Microsoft/VSProjectSystem/blob/async-hang-debugging/doc/overview/VS2013_vs_VS2015.md) for dynamic-enum-provider and failed.

**Isn't there anything extra required or this feature doesn't work in VS2015 RC yet?**

My package is MEF-enabled. I apply `ExportDynamicEnumValuesProvider` to class implementing `IDynamicEnumValuesProvider` interface and nothing actually happens (when project with such a rule is loaded). However the same class works fine in VS2013 using `Export` and `DynamicEnumCategory`.

Project and provider implemenation can be found [here](/phofman/vs-plugin/blob/develop/src_vs2012/Package/MSBuildExtensions/ValueProviders/CompilerVersionsProvider.cs).

Thanks

**Comment by AArnott** [comment]
It looks like your exported type is missing both `[AppliesTo]` for VS2015 and `[PartMetadata(...)]` as described in the migration doc. VS2013 let you get away with it by just letting your export apply everywhere if you were missing the attribute. VS2015 locks this down by ignoring your extension if you forgot to add it.
