### ISSUE TITLE
Adding Custom Context Command for Solution Explorer Item

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/VSProjectSystem#40]
How would you add a custom context command for a specific file/folder in the Solution Explorer?  As an example, let's say I right-click a file named (MyScript.py).  I would like a custom command to only be shown if it was a specific file name (or possibly specific extension) in my project.

**Comment by AArnott** [comment]
1. [Define your custom command](https://msdn.microsoft.com/en-us/library/bb164627.aspx)
2. [Export a command handler](doc/extensibility/command_handlers.md) to handle it. When invoked, your extension will be fed info on what item(s) are selected when the user invokes the context menu and you'll then be able to determine whether your command should be visible, enabled, etc.

**Comment by shaggygi** [comment]
https://github.com/Microsoft/VSProjectSystem/blob/7574fa86b12a8ed8bf9bbb633de4588b98c7a87e/doc/extensibility/command_handlers.md

**Comment by AArnott** [comment]
Oops. Sorry about the broken link. I've repaired it inline.
