### ISSUE TITLE
Replace "CPS" references

### ISSUE THREAD

**Issue by AArnott** [Microsoft/VSProjectSystem#5]
We should refer to CPS in the docs consistently with its new moniker of "Visual Studio project system" or "project system extensibility SDK".

**Comment by AArnott** [comment]
Before we really get started on this, we may want to firm up plans as to how to go about it. For example we'll need to find reasonable substitutes for terms such as "CPS Core" and "CPS VS"

**Comment by AArnott** [comment]
Rejected because the guidance to avoid the CPS term is unfounded.

**Comment by SamB** [comment]
I'd go even further than @AArnott and say that the term Common Project System is actually *underused* (though not necessarily in the this documentation).
