### ISSUE TITLE
Project types should be able to restrict values entered via IDynamicEnumValuesProvider

### ISSUE THREAD

**Issue by adrianvmsft** [Microsoft/VSProjectSystem#53]
CPS never calls the following methods from `IDynamicEnumValuesGenerator`

`AllowCustomValues` - when specifying false, the values it should not allow random strings
`TryCreateEnumValueAsync` - when random string entered, it should be called in order to attempt to match the entered value against allowed values

**Comment by WillBuik** [comment]
Looks good.
