### ISSUE TITLE
Adding Custom References Node with IProjectTreeProvider

### ISSUE THREAD

**Issue by FreddyDgh** [microsoft/VSProjectSystem#57]
The [Custom Reference Types](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/custom_reference_types.md) pages says that "You can define a References node by exporting  IProjectTreeProvider . Implementations of this interface should derive from  ProjectTreeProviderBase ."

I've found a couple aspects of this to be confusing:

1) If I use `[AppliesTo(MyUnconfiguredProject.UniqueCapability)]` on the IProjectTreeProvider export, my implementation of ProjectTreeProviderBase doesn't get called.  If I do `[AppliesTo("")]` instead, my code is called, but obviously is getting applied to more project types than I want.  I am only trying to target a new project type that I am creating - is there any reason that `[AppliesTo(MyUnconfiguredProject.UniqueCapability)]` shouldn't produce the desired effect?

2) As far as adding the actual node for the References Folder, I gathered that I should be using the `NewTree()` method of ProjectTreeProviderBase to create the new node, but if that's the case, I'm not seeing where/how to add this node to the existing tree.  Any further clarifications on this?

**Comment by AArnott** [comment]
Regarding 1), your capability must be defined at the UnconfiguredProject scope and it probably isn't.  Once you ship your .targets in a well-known location and your project templates refer to it at that location it should resolve the issue. In the meantime, you can add the capability at the unconfigured project scope by adding this XML to your project (template) just above the `</Project>` closing tag:

```xml
<ProjectExtensions>
    <ProjectCapabilities>
      <UniqueCapability />
    </ProjectCapabilities>
</ProjectExtensions>
```

For 2), we badly need to enhance the [documentation here](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/IProjectTreeProvider.md)

**Comment by aienabled** [comment]
Any updates? I'm also curious how to use the `NewTree()` method.

**Comment by dazinator** [comment]
I'd also love to know how to use this class, as I am hitting issues with the default one it seems (PhysicalProjectTreeProvider)

**Comment by Tobist** [comment]
Hi,
I am using the [Export(ExportContractNames.ProjectTreeProviders.PhysicalViewRootGraft, typeof(IProjectTreeProvider))]

and there I create the Tree withing the SubmitTreeUpdateAsync((t, a, c) => Task.FromResult(new TreeUpdateResult(SomeTree, lazyFill: true)));

You can even register Subscriptions to react on project changes.

But at this point I have to create a new Provider for every node I want to have under the root-project node. Addiotionally I am trying to find out how to delete the old/common project Provider. (I want to replace the normal projectsystem by my own treeproviders)

Cheers

**Comment by Tobist** [comment]
The NewTree()-Method is used like that in my case 
```csharp
IProjectTree newDatabaseNode = this.NewTree(
                    caption: Path.GetFileName(path),
                    filePath: path,
                    icon: KnownMonikers.Reference.ToProjectSystemType(),
                    capabilities: new string[] { ProjectTreeCapabilities.FileOnDisk, ProjectTreeCapabilities.NonMemberItem, ProjectTreeCapabilities.FileSystemEntity, ... }
                    );

**Comment by dazinator** [comment]
@FreddyDgh you've closed this issue but can you comment on why / what the resolution was?

**Comment by drewnoakes** [comment]
I can't comment as to why this was closed, but if you're looking for real-world examples of such project tree providers, you can reference these two from SDK-style projects:

- The [Dependencies tree](https://github.com/dotnet/project-system/blob/7df0c3482c0d5f2162ec0e6bd21f405c77d4b5f0/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/Dependencies/DependenciesProjectTreeProvider.cs).
- The [Imports tree](https://github.com/dotnet/project-system/blob/7df0c3482c0d5f2162ec0e6bd21f405c77d4b5f0/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Tree/ProjectImports/ImportTreeProvider.cs).
