### ISSUE TITLE
Remove MicroBuild dependency in public NuGet package

### ISSUE THREAD

**Issue by AArnott** [Microsoft/VSProjectSystem#58]
A MicroBuild NuGet package dependency was inadvertently added to the [publicly released NuGet packages](https://www.nuget.org/packages/microsoft.visualstudio.projectsystem)
We also are forcing a dependency on `Nerdbank.GitVersioning` on people. :(

We should remove this (by adding `developmentDependency="true"` to those entries of our packages.config files).

**Comment by kovalikp** [comment]
You might want to add `<developmentDependency>true</developmentDependency>` to your MicroBuild package nuspecs.

**Comment by AArnott** [comment]
@kovalikp We've already done this, but perhaps we're using an older version of MicroBuild that didn't have this. Also, a nuget client bug (that has since been fixed) would ignore the nuspec file for this anyway, which might cause regressions like this.

**Comment by adrianvmsft** [comment]
Fixed in the new version of the NuGet packages (14.0.50729-pre)
