### ISSUE TITLE
[Question] Get Full C# Intellisense in new project system

### ISSUE THREAD

**Issue by jkoritzinsky** [Microsoft/VSProjectSystem#76]
I've been trying to create a new Project System that still uses C# source files.  I've had a persistent issue where Intellisense only sees types defined in referenced assemblies that are in the Framework folder of the "Add Reference" dialog. My projects are requiring .NET 3.5 if that makes a difference.

(These is for making it easier to make mods for Kerbal Space Program.)

**Comment by jviau** [comment]
@jkoritzinsky are you using the Project System Extensibility? The default project type generated by it has the necessary C# targets to enable intellisense. If you want to easily view the project capabilities you can install [show project imports](https://visualstudiogallery.msdn.microsoft.com/65a7d5ca-684f-4d2a-b72c-6d1f1d74353e) extension. After installing it, restart VS and open a project of your type. There will be a new "imports" node in the solution explorer. For C# intellisense you should be importing Microsoft.CSharp.targets at some level.

**Comment by jkoritzinsky** [comment]
I am using the Project System Extensibility.  I have Microsoft.CSharp.targets imported in CustomProjectCs.targets (checked with the extension you recommended).  I tried to get Intellisense again and it still isn't working except for "Framework" assemblies.

Any other ideas?

**Comment by jkoritzinsky** [comment]
I'm also not getting intellisense on a new project just after being created from the template.  Specifically, the code completion suggestions do not include anything not from one of the Framework Assemblies.  Additionally, colorization does not work for classes from assemblies not in the "Framework Assemblies" group.

**Comment by jviau** [comment]
What version of Visual Studio are you using? Do you get intellisense for regular C# projects?

**Comment by jkoritzinsky** [comment]
I'm using Visual Studio 2015 Community.  I get intellisense for regular C# projects.

A few additional things I've noticed:
* Whenever I create a new project with a brand new CPS project type and try to add a reference, I get an error about a missing "TargetWinMDFrameworkLocation" or something very similar.  I've fixed this one by removing the capability of adding WinMD references to the project type.
* Whenever I build, I get an "ambiguous reference" error from MSBuild on the `Microsoft.VisualStudio.ComponentModelHost` assembly.  I've been able to manually resolve this one by adding a hint-path in the .csproj file.
* I also have Visual Studio 2013 Professional installed.

**Comment by jkoritzinsky** [comment]
@jviau I just tried creating a new C# class library project and making it a CPS project as shown in the turn_on_cps_for_csharp_vb_project.md documentation in the repo.  I immediately lost all Intellisense (same situation as the new project type).  I'm thinking it might be something with my Visual Studio install.  Any ideas?

**Comment by aienabled** [comment]
I also had this issue. I've investigated and resolved it:
1. By default, there is a property
`<TargetFrameworkMoniker>.NETFramework,Version=$(TargetFrameworkVersion)</TargetFrameworkMoniker>` at `CustomProject.Default.Props`. There is also `<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>` right above it. I've fixed it by assigning specific version for $TargetFrameworkMoniker: `<TargetFrameworkMoniker>.NETFramework,Version=4.6.1</TargetFrameworkMoniker>`.

2. Also it was required to import CSharp targets directly at the project file, even if you importing them at your targets file. Just add this line
`<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />`

**Comment by jkoritzinsky** [comment]
@aienabled That worked! Awesome!  Thanks for your help!

**Comment by dazinator** [comment]
Thanks @aienabled  - importing the `Microsoft.CSharp.targets` directly in the proj file was enough to fix it for my case! How on earth did you discover that solution.. thank you! :)

**Comment by dazinator** [comment]
One step forwards, another step backwards.. moving the import of Microsoft.CSharp.targets to the project file has fixed intellisense issues, but broken assembly references - doh. I guess project systems are not for the faint of heart :) - I'll randomly play around with the order of imports etc until hopefully things work.

**Comment by dazinator** [comment]
Success! The solution for me in the end:

1. Scrap the `CustomProjectCs.targets` file, move it's contents directory into the `CustomProject.targets` file.
2. In your project file, change the import of `CustomProjectCs.targets` to `CustomProject.targets` instead.
3. Underneath that, add the import for `Microsoft.CSharp.targets`

**Comment by aienabled** [comment]
@dazinator, assembly references works fine for me together with intellisense. Maybe some specific order required... from my project file:
```
<Import Project="$(CustomProjectExtensionsPath)CustomProject.Default.props" />
<!-- ... configurations here ... -->
<Import Project="$(CustomProjectExtensionsPath)CustomProject.props" />
<!--  ... project items here  ...  -->
<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
<Import Project="$(CustomProjectExtensionsPath)CustomProjectCs.targets" />
```

And `CustomProject.Default.props` defines this:
```
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props"
	        Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
```

CustomProject.targets defines capabilities:
```
<ItemGroup>
		<ProjectCapability Include="AtomicTorch.GameEngine.ModProject" />
		<ProjectCapability Include="AssemblyReferences;ProjectReferences" />
		<ProjectCapability Include="AllTargetOutputGroups;VisualStudioWellKnownOutputGroups" />
		<ProjectCapability Include="ProjectConfigurationsDeclaredAsItems" />
</ItemGroup>
```

BTW, I'm using ReSharper and its auto-complete feature (together with some other features) sometimes stops working until I remove and add Microsoft.CSharp.targets again. I've reported the issue and the fix will be available with ReSharper 10.1. https://youtrack.jetbrains.com/issue/RSRP-452621

**Comment by dazinator** [comment]
Thanks @aienabled  - you were right, it was an ordering issue!

**Comment by adrianvmsft** [comment]
In VS 2017, the "C#" functionality is now official as part of the [roslyn project system](https://github.com/dotnet/roslyn-project-system) - currently use by .Net Core projects.

Project systems that would like to provide C# related experience should look into tailoring the experience provided by the roslyn project system.

On the VS Project System, we are moving away from the C#-like default experience to a more simplified implementation, similar to #184

That makes this particular issue no longer relevant.

**Comment by aienabled** [comment]
@adrianvmsft, thanks for informing us.

I'm glad to say that currently we have no problems with C# support. Roslyn Project System works fine for us, the only thing required to add proper support for C# is only include of CSharp targets file `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />` in `csproj`. And this is not required if Roslyn Project System is activated with `<Project Sdk="Microsoft.NET.Sdk">` (it will include the targets automatically).
