### ISSUE TITLE
Analyzers not using proper package layout

### ISSUE THREAD

**Issue by SamB** [Microsoft/VSProjectSystem#82]
So, there is now a convention for where to put analyzers in a NuGet package, and it's important to follow this convention if you want them to work properly with anything other than the old `packages.config` format, since that's the only situation in which `install.ps1` and `uninstall.ps1` will ever run: neither [Paket](https://fsprojects.github.io/Paket/analyzers.html) nor [NuGet v3 in `project.json` mode](https://docs.nuget.org/create/analyzers-conventions) will pick up analyzers that aren't located according to the convention.

The convention is basically to put analyzers in an `analyzers/dotnet` directory within their package, and to further split any language-specific analyzer DLLs into `cs` and `vb` subdirectories under that.  (Or you could follow the links above for the details, most of which are fairly irrelevant so far.)

Btw, this concerns the packages:

* Microsoft.VisualStudio.ProjectSystem.Analyzers (14.0.50729-pre)
* Microsoft.VisualStudio.Threading.Analyzers (14.1.114-pre)

(Not sure the latter is strictly-speaking yours, but the package doesn't exactly point at a bug tracker and your "Project Type" template pulls it in, so I might as well list it while I'm here ...)

**Comment by AArnott** [comment]
While you are correct regarding the new pattern, we need to continue to work for packages.config scenarios, as that is the only supported package consumption for class libraries that would build extensions for the VS2015 SDK. 
If the new folder layout in the nuget package works in both worlds, then adoption of the new format seems like a reasonable move.

**Comment by SamB** [comment]
@AArnott: To work in both worlds, you just need to use the new layout (for the new world) *and* the powershell scripts (for the old world); there is some stuff about this further down https://docs.nuget.org/create/analyzers-conventions.  And yes, I do realize that using project.json the way e.g. roslyn does is not technically "supported" *yet*, and that Paket isn't supported by MS at all (and probably never will be).

**Comment by AArnott** [comment]
Good to hear. Thanks for confirming.

**Comment by adrianvmsft** [comment]
Fixed in 14.1.127.50932 and newer builds. For existing project types, please reference to the workaround above.
