### ISSUE TITLE
Item types missing from the "Add Item" dialog

### ISSUE THREAD

**Issue by YaakovDavis** [Microsoft/VSProjectSystem#85]
I added a new item type following the instructions here:
https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/contentitem_types.md

I modified the ProjectItemsSchema.xaml and .targets files.
I then added an item template as described in the referenced MSDN article.

However, I till don't see the item in the dialog.
Also, I couldn't find an example for this in the nuproj reference implementation.

**Comment by adrianvmsft** [comment]
I think you will need to add an "AppliesTo" element to the item template that points to your project's unique capability

I tried this out, and updated the documentation with step by step instructions explaining how to do that. It worked for me after I added that element. 

Please take a look and let me know if that works for you.
#87

Thanks,
Adrian

**Comment by YaakovDavis** [comment]
This works, thanks!
As a side note, it's worth mentioning in the rule's .xaml comments which .targets file needs to be modified (there're 2 .targets files).
