### ISSUE TITLE
Creating a Custom Console Application Project Template

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/VSProjectSystem#89]
I am probably overlooking something, but how do you create a custom Console Application project template?  What changes do you have to make after adding New Project > Project Template?

Basically, I need to add some code and NuGet references to a Console Application.

Any help is appreciated.

**Comment by adrianvmsft** [comment]
Not sure I completely understand your question... Project System Extensibility already creates a project template by default when you create a new Project Type.

If you are referring to VS SDK in general, you typically need to:
- create a new VSIX project
- add a new item - "Project Template"
- edit the vsix manifest, under assets - add the project template

For more details, you can take a look at this page that explains how to add an item template for a custom item type: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/contentitem_types.md

Nuget adds an extra layer of complexity as you need to package the set of nuget packages within the vsix itself. For more information you can refer to this page:
http://docs.nuget.org/Create/Packages-in-Visual-Studio-Templates

Hope this helps,
Adrian

**Comment by shaggygi** [comment]
This helps.  Thanks for the links.

**Comment by adrianvmsft** [comment]
Great! In that case, I am going to close this issue.
