### ISSUE TITLE
[Question] - DebuggerFlavor possible choices?

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#92]
By default, in `CustomProject.Default.props` - I can see:

 `<DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>`

Is anyone able to explain or point to some documentation (I googled but all I found was this which doesn't tie up to the value directly: https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.vcprojectengine.edebuggertypes.aspx) that explains what this value is and what other possible options might be?

For my project system, I would like to customise the debug experience so that when they click Debug, I want to "attach" to a locally running process automatically - so naturally I am wondering if this setting is relevant.

**Comment by aienabled** [comment]
The default debuggers (WindowsLocalDebugger and WindowsRemoteDebugger) are provided by default capabilities. So they're provided if you:
1. import default CSharp targets (`<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />`) - which is done by default
2. do not disallow common capabilities definition (by default they're allowed). You could disallow common capabilities by adding:
```
<PropertyGroup>
	<DefineCommonCapabilities>false</DefineCommonCapabilities>
	<DefineCommonReferenceSchemas>false</DefineCommonReferenceSchemas>
</PropertyGroup>
```
at your custom project type targets file before `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />`.


If you need customized debugger, you could create your own debugger launcher by following this guide https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/IDebugLaunchProvider.md

**Comment by dazinator** [comment]
Thanks again @aienabled !
