### ISSUE TITLE
[Question] - Enabling NuGet to be used?

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#94]
If I hit f5 to start an experimental instance, and then create a new project based on my project type, if I then try to use NuGet package manager to add a NuGet package - I get this error:

![image](https://cloud.githubusercontent.com/assets/3176632/11985074/1c917998-a9b9-11e5-8eb5-03c73e66edef.png)

If I look at my project properties page I can see:

![image](https://cloud.githubusercontent.com/assets/3176632/11985107/5f3be882-a9b9-11e5-8954-4655d885e156.png)

And in my `CustomProject.Default.props` file:

```xml

  <TargetPlatformVersion>7.0</TargetPlatformVersion>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>    
    <TargetFrameworkProfile></TargetFrameworkProfile>
    <TargetFrameworkMoniker>.NETFramework,Version=$(TargetFrameworkVersion)</TargetFrameworkMoniker>

```
I don't understand why NuGet is saying the project targets `Unsupported,Version=v0.0` - any pointers would be greatly appreciated!

**Comment by dazinator** [comment]
I'm delving into NuGet source code to see how it works out what the target framework is: https://github.com/NuGetArchive/NuGet.PackageManagement/blob/8d71f873145366a7a2938da196b3374f401f91fd/src/PackageManagement/NuGetPackageManager.cs#L671

**Comment by dazinator** [comment]
I think.. this is related to the fact that when my new project is created, it intalls a nuget package that modifies the project file during installation. This in turn prompts a "reload project" dialog. If I click "Reload" - i notice that NuGet then encounters this issue where it thinks the target framework is `Unsupported,Version=v0.0`. If I don't reload, then NuGet works fine and thinks it is: `.NETFramework,Version=v4.0`

So the moral of this story is, don't add any NuGet packages to your project type that will prompt a "reload" of your project when its created..

**Comment by aienabled** [comment]
I have the same issue even without the reload - right after opening the solution with project (not new one) and trying to restore nuget dependencies ("packages" folder removed).
Could you try please removing "packages" folder and opening your solution?

**Comment by dazinator** [comment]
I tried this but I get a predicted error - basically my nuget package contains a targets file that the project imports. So if I delete the packages folder, it deletes the targets, then when I attempt to open the project, I get the following which is kind of expected I guess..

![image](https://cloud.githubusercontent.com/assets/3176632/14590432/4bcd0c7e-04f2-11e6-9eca-ef6e8c7eec47.png)

Then right clicking on the project and selecting "reload":

![image](https://cloud.githubusercontent.com/assets/3176632/14590428/41f834c6-04f2-11e6-9130-8e784ded4916.png)


In an ideal world, i'd somehow be able to trigger a nuget package restore to put the package containing the targets file back.. 

Not sure how to deal with this yet, so I am flat out just saying you have to check packages in.. :(
