### ISSUE TITLE
Supporting NuGet packages that need to access Microsoft.Build.Evaluation.Project

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#95]
I have noticed that when I create a new project based on my project type, if I then look at the `GlobalProjectCollection` object, by going to the package manager console and doing:

```
> Add-Type -AssemblyName 'Microsoft.Build, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
> $msBuildProjects = [Microsoft.Build.Evaluation.ProjectCollection]::GlobalProjectCollection
> $msBuildProjects
```

It shows that the `GlobalProjectCollection` object does not contain my project.

If I add a new C# library project to the same solution however, then this project gets added to the `GlobalProjectCollection`.

This is causing issues because I have a NuGet package that upon installation, runs powershell to grab the `Microsoft.Build.Evaluation.Project` from the `GlobalProjectCollection` so that it can import some additional targets - it doesn't find my project.

Any ideas on how I can fix this situation? I assumed VS added all project types to this collection automatically!

**Comment by GearedToWar** [comment]
You are right in your observation that CPS projects are not loaded in the GlobalProjectCollection object.
The collection is not thread-safe and its use is discouraged.

To get access to a loaded project, you need to [obtain the IProjectLockService](https://github.com/Microsoft/VSProjectSystem/blob/94bd2eac351477d37a4e2a80d32e73a4e1bbd347/doc/automation/obtaining_the_IProjectLockService.md#obtaining-the-iprojectlockservice) and then [get the loaded MsBuild project] (https://github.com/Microsoft/VSProjectSystem/blob/94bd2eac351477d37a4e2a80d32e73a4e1bbd347/doc/automation/obtaining_the_MSBuild.Project_from_CPS.md).

**Comment by dazinator** [comment]
Thanks @GearedToWar  - any idea how that can be done through powershell though - which typically has to use `EnvDTE` ?

The problem is that many NuGet packages use [this technique](http://blogs.clariusconsulting.net/kzu/how-to-add-an-msbuild-import-to-a-project-on-nuget-install/) to grab the project from that collection - so if my project isn't present then it cannot support those NuGet packages properly. However, I'd settle for figuring our alternative powershell that works for CPS projects so at least support could be added to these NuGet packages in the future for CPS based projects!

**Comment by dazinator** [comment]
Also - I am aware that the powershell install script for a NuGet package, could "shell out" to an executable which can load a new MSBuild project from the current project file, and manipulate it that way, but this results in VS prompting the user to reload the project because changes are being made outside of the solution, so this isn't really desirable.

**Comment by dazinator** [comment]
Ah think I have found the way forward.. should be [able to do this](http://weblogs.asp.net/cazzu/GetServiceFromDTE) in powershell script to get the `IServiceProvider`:  From there, can follow the docs to get the project lock service etc

**Comment by dazinator** [comment]
So far I have managed to get as far as determining its a CPS project:
```
$vsSolutionObject = [Microsoft.VisualStudio.Shell.Package]::GetGlobalService([Microsoft.VisualStudio.Shell.Interop.IVsSolution])
$vsSolution = Get-Interface $vsSolutionObject ([Microsoft.VisualStudio.Shell.Interop.IVsSolution])
$projectHierarchyObject = $null
$project = Get-Project
$result = $vsSolution.GetProjectOfUniqueName($project.UniqueName,([ref]$projectHierarchyObject))
#$vsProjectHierarchy = Get-Interface $projectHierarchyObject ([Microsoft.VisualStudio.Shell.Interop.IVsHierarchy])
$isCpsProject = [Microsoft.VisualStudio.Shell.PackageUtilities]::IsCapabilityMatch($projectHierarchyObject, "CPS")


```
The bit I am stuck on now, is getting to the `IVsBrowseObjectContext` to grab the lock service. Have tried:

```
Add-Type -AssemblyName 'Microsoft.VisualStudio.ProjectSystem.V14Only, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 $browsableProjectContext = [Microsoft.VisualStudio.ProjectSystem.Designers.IVsBrowseObjectContext]::$project.Object

```
 
But no joy :(

And then even once I manage to get the LockService, I have no idea whether you can `await` an async method in powershell - my guess is you can't, so absolutely no idea how to consume the lock servide once I actually get it, i'e I'd need to do the following but in powershell:
```
// How to do this in powershell with the $projectLockService?

 using (var access = await projectLockService.WriteLockAsync())
        {
            MSBuild.Project project = await access.GetProjectAsync(configuredProject);

            // party on it, respecting the type of lock you've acquired. 

            // If you're going to change the project in any way, 
            // check it out from SCC first:
            await access.CheckoutAsync(configuredProject.UnconfiguredProject.FullPath);
        }

```

**Comment by aienabled** [comment]
Regarding the second question. When you need to await for an async operation result at PowerShell, you can directly access "Result" property of the returned Task object. I mean you could use this `access.CheckoutAsync(configuredProject.UnconfiguredProject.FullPath).Result`
instead of `await access.CheckoutAsync(configuredProject.UnconfiguredProject.FullPath)`.

**Comment by dazinator** [comment]
@aienabled thanks, handy to know! Don't think in this particular case accessing the Result will work- as it says your code will hang: https://github.com/Microsoft/VSProjectSystem/blob/94bd2eac351477d37a4e2a80d32e73a4e1bbd347/doc/automation/obtaining_the_MSBuild.Project_from_CPS.md

I'll read the threading rules docs though, there should be some way for me to safely consume the task i'd hope! :)

**Comment by aienabled** [comment]
[b]dazinator[/b], yes, I've read these rules. I think it deserves to try if you out of luck with other solutions.

**Comment by dazinator** [comment]
@aienabled good point - i'll definately give it a go!

**Comment by dazinator** [comment]
So have managed to get the `IProjectLockService` from powershell:

```
 Add-Type -AssemblyName 'Microsoft.VisualStudio.ProjectSystem.V14Only, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

 $vsSolutionObject = [Microsoft.VisualStudio.Shell.Package]::GetGlobalService([Microsoft.VisualStudio.Shell.Interop.IVsSolution])
    $vsSolution = Get-Interface $vsSolutionObject ([Microsoft.VisualStudio.Shell.Interop.IVsSolution])
$projectHierarchyObject = $null
$project = Get-Project
    $result = $vsSolution.GetProjectOfUniqueName($project.UniqueName,([ref]$projectHierarchyObject))
$projectLockService = $vsProjectHierarchy.UnconfiguredProject.ProjectService.Services.ProjectLockService   

```

Next step - need to try using the async API to consume a lock..

**Comment by dazinator** [comment]
As `projectLockService.WriteLockAsync()` doesn't return a `Task` I can't call `.Result` on it, looking at the API i'll try and do: `projectLockService.WriteLockAsync().GetAwaiter().GetResult();` instead..

**Comment by dazinator** [comment]
I am really stuck on this, so far I have managed to get at the `IProjectLockService` from powershell but as I cannot use `await` in powershell I have tried to find an appropriate synchronous API. Nothing I have tried has worked. The following shows me doing the equivalent of `projectLockService.WriteLockAsync().GetAwaiter().GetResult();` however when it calls `GetResult` that just causes an error: `An internal error occurred. Please contact Microsoft Product Support Services..`

```powershell

Write-host "Attempting to consume project lock."               
$awaitable = $projectLockService.WriteLockAsync() 
Write-host "DnnPackager: Got awaitable."     
$vspAwaitable = $awaitable -as [Microsoft.VisualStudio.ProjectSystem.ProjectWriteLockAwaitable]
$awaiter =  $vspAwaitable.GetAwaiter()    
Write-host "DnnPackager: Got awaiter."                 
$vspAwaiter = $awaiter -as [Microsoft.VisualStudio.ProjectSystem.ProjectWriteLockAwaiter]
$access = $vspAwaiter.GetResult()
Write-host "DnnPackager: Got result."      # never reaches this far.

```

**Comment by dazinator** [comment]
- Found a way forward, and that's to embed the csharp code in the powershell script like this:

```powershell

$Assem = ( 
    "Microsoft.VisualStudio.ProjectSystem.V14Only, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" , 
    "Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" 
    ) 

    $Source = @" 
using Microsoft.Build.Evaluation;
using Microsoft.VisualStudio.ProjectSystem;
using System;
using System.Threading.Tasks;

namespace DnnPackager.Install
{
    public static class CpsHelper
    {
        public static async Task<Project> GetMsBuildProject(IProjectLockService projectLockService, UnconfiguredProject unconfiguredProject)
        {
            if(projectLockService == null)
            {
                throw new ArgumentNullException("projectLockService");
            }

            if(unconfiguredProject == null)
            {
                throw new ArgumentNullException("unconfiguredProject");
            }

            using (var access = await projectLockService.WriteLockAsync())
            {

                var configuredProject = await unconfiguredProject.GetSuggestedConfiguredProjectAsync();
                Project project = await access.GetProjectAsync(configuredProject);

                // party on it, respecting the type of lock you've acquired. 

                // If you're going to change the project in any way, 
                // check it out from SCC first:
                await access.CheckoutAsync(configuredProject.UnconfiguredProject.FullPath);

                return project;
            }
        }
    }
}
"@ 

Add-Type -ReferencedAssemblies $Assem -TypeDefinition $Source -Language CSharp  
$msBuildProjectTask = [DnnPackager.Install.CpsHelper]::GetMsBuildProject($projectLockService, $unconfiguredProject)

$msBuildProject = $msBuildProjectTask.Result

```

I'm not sure if I can pass in a callback / delegate as an argument, such that I can have some powershell method be invoked from c# whilst the lock is being consumed. If not it means I will have to move a lot of my powershell into the C# method so that it can modify the project within the using statement.

**Comment by dazinator** [comment]
I finally managed to achieve this, by writing a helper method in a C# assembly. I load the assembly in powershell, and invoke the helper method. The C# helper method can use async / await etc and it consumes the lock service and modifies the project, then frees the lock as per the documentation. It returns a `Task` so that the powershell can `Wait` for this that task to finish. 

This was a big pain though, perhaps CPS projects can make it easier for NuGet package authors to get at the MSBuild project in future - or perhaps NuGet itself could do this.
