### ISSUE TITLE
[Question] Multi-file Item Templates

### ISSUE THREAD

**Issue by dazinator** [Microsoft/VSProjectSystem#99]
I have created a "multi-item" template, it's for an ascx file, so that when the user adds the ascx file to the project, it adds the designer and the code behind file as well.

This is working in that it adds the files, but they don't end up nested together in solution explorer, e.g they end up looking like this:

![image](https://cloud.githubusercontent.com/assets/3176632/12028169/e85985d8-adca-11e5-8688-92bb760011f6.png)

I followed [these docs](https://msdn.microsoft.com/en-us/library/ms247115.aspx) when defining the vstemplate file:

```xml
  <TemplateContent>
    <References>
      <Reference>
        <Assembly>System</Assembly>
        <Assembly>System.Web</Assembly>
      </Reference>
    </References>
    <ProjectItem SubType="" TargetFileName="$fileinputname$.ascx" ReplaceParameters="true">View.ascx</ProjectItem>
    <ProjectItem SubType="ASPXCodeBehind" TargetFileName="$fileinputname$.ascx.cs" ReplaceParameters="true">View.ascx.cs</ProjectItem>
    <ProjectItem SubType="" TargetFileName="$fileinputname$.ascx.designer.cs" ReplaceParameters="true">View.ascx.designer.cs</ProjectItem>   
  
  </TemplateContent>

```

Is there something I could be missing?

**Comment by aienabled** [comment]
This way you just adding these items to the project file, but the project system doesn't know how to properly process them (that these files should be nested, compiled with specific build tool, etc).

What you need to do, is define [custom item type](https://github.com/Microsoft/VSProjectSystem/blob/94bd2eac351477d37a4e2a80d32e73a4e1bbd347/doc/extensibility/custom_item_types.md). However the tutorial by this link doesn't describe how to add support for nested/dependent files.

I will post an with example of adding XAML Page type to your project system (which has dependent .xaml.cs file and displayed as nested if all done properly, it will also participate with MSBuild if you defined common CSharp targets). You could implement support for ASCX in a similar way.

First, you need to define a Rule to acknowledge Project System about new item type:
(place to BuildSystem/Rules/PageXaml.xaml, BTW, you could use a Xaml Rule item template for this)
```
<Rule
    Name="PageXaml"
    DisplayName="PageXaml"
    PageTemplate="tool"
    Description="PageXaml build items"
    xmlns="http://schemas.microsoft.com/build/2009/properties">
    <Rule.DataSource>
        <DataSource Persistence="ProjectFile" HasConfigurationCondition="True" ItemType="Page" />
    </Rule.DataSource>

    <StringProperty Name="Identity" DisplayName="File Name" ReadOnly="true" Category="Misc">
        <StringProperty.DataSource>
            <DataSource Persistence="Intrinsic" ItemType="Page" PersistedName="Identity" />
        </StringProperty.DataSource>
    </StringProperty>

    <StringProperty Name="FullPath" DisplayName="Full Path" ReadOnly="true" Category="Misc">
        <StringProperty.DataSource>
            <DataSource Persistence="Intrinsic" ItemType="Page" PersistedName="FullPath" />
        </StringProperty.DataSource>
    </StringProperty>

    <BoolProperty Name="Visible" Visible="False" />
    <StringProperty Name="DependentUpon" Visible="false" />
    <StringProperty Name="Link" Visible="false" />
</Rule>
```

Second, you need to edit `ProjectSchemaDefinitions.xaml` and define ContentType, ItemType and FileExtension:

```
    <!-- XAML -->
    <ContentType
        Name="PageXaml"
        DisplayName="XAML Page"
        ItemType="Page">
        <NameValuePair Name="DependentFileExtensions" Value=".cs" />
        <NameValuePair Name="DefaultMetadata_SubType" Value="Designer" />
        <NameValuePair Name="DefaultMetadata_Generator" Value="MSBuild:Compile" />
    </ContentType>

    <ItemType Name="Page" DisplayName="Page" />

    <FileExtension Name=".xaml" ContentType="PageXaml" />
```
(please note that here used "DependentFileExtensions" pair, it defines files nesting).

Third, you need to edit your targets-file to add support for properties browser for this item type:
```
<PropertyPageSchema Include="$(MSBuildThisFileDirectory)Rules\PageXaml.xaml;">
	<Context>File;BrowseObject</Context>
</PropertyPageSchema>
```

if you done this correctly, you could try to add existing UserControl XAML-file with its code-behind .XAML.CS-file and it will properly appear into the project tree and will be built by MSBuild (if you define common CSharp targets).

Regards!

**Comment by dazinator** [comment]
@aienabled - wow thank you so much for your help with this and putting me on track. I'll give this a go! :-)

**Comment by dazinator** [comment]
@aienabled - I have go to this part:
> Second, you need to edit ProjectSchemaDefinitions.xaml and define ContentType, ItemType and FileExtension:

My project does not have this rule file. Is this a sing that something is wrong, or should I just create a new file? These are the rules in my project that were created by default:

![image](https://cloud.githubusercontent.com/assets/3176632/12036004/f65d25d0-ae39-11e5-8992-c77185aaf02f.png)

**Comment by dazinator** [comment]
@aienabled  ignore me - It clarifies that [I need to create that file](https://github.com/Microsoft/VSProjectSystem/blob/94bd2eac351477d37a4e2a80d32e73a4e1bbd347/doc/extensibility/custom_item_types.md) on the link you have provided.

**Comment by dazinator** [comment]
Part way there!

![image](https://cloud.githubusercontent.com/assets/3176632/12036557/04508ee8-ae3f-11e5-909c-aab60ef064c2.png)

Just need to figure out how get the designer file nested under the .cs file.

**Comment by dazinator** [comment]
Found some more docs here: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/extensibility/automatic_DependentUpon_wireup.md

**Comment by dazinator** [comment]
Ok, it doesn't look like you can specify the extra level of nesting that I want, atleast - I am not sure how to do it within a single content type. Here is what I have so far:

```xml

<ContentType
        Name="UserControl"
        DisplayName="User Control"
        ItemType="Content">
        <NameValuePair Name="DependentFileExtensions" Value=".cs;.designer.cs" />       
        <NameValuePair Name="DefaultMetadata_SubType" Value="Designer" />
        <NameValuePair Name="DefaultMetadata_Generator" Value="MSBuild:Compile" /> 
    </ContentType>

 <ItemType Name="Content" DisplayName="Content" />

<FileExtension Name=".ascx" ContentType="UserControl" />

```

But that only results in both files being nested under the same parent:

```
-View.ascx
    -View.ascx.cs
    -View.ascx.designer.cs
```

And I would like the `designer.cs` file nested under the `.cs` file, which in turn is nested under the `ascx` file like this:

```
-View.ascx
    -View.ascx.cs
        -View.ascx.designer.cs
```

I'm going to play around some more, perhaps I have to add a content type specifically for the `ascx.cs` file so that I can specify it's nesting criteria.

I would also like the `.cs` file to be given a SubType of `ASPXCodeBehind`
All in all I'm after this in the project file:
```xml
 <ItemGroup>
    <Content Include="Web.config" />
    <Content Include="WebUserControl1.ascx" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="WebUserControl1.ascx.cs">
      <DependentUpon>WebUserControl1.ascx</DependentUpon>
      <SubType>ASPXCodeBehind</SubType>
    </Compile>
    <Compile Include="WebUserControl1.ascx.designer.cs">
      <DependentUpon>WebUserControl1.ascx</DependentUpon>
    </Compile>
  </ItemGroup>
```

I'll raise a seperate issue for this if I can't figure it out.

**Comment by dazinator** [comment]
Nope no joy. I'll raise a more concise issue.
